package UI;

import Classes.Product.ProductsImp;
import Classes.Product.SetOfProducts;
import Classes.Product.productObserverImp;
import Classes.payment.SalesCart;
import Classes.payment.SetOfCart;
import Classes.serialization.Serialization;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lakmi
 */
public class Cart extends javax.swing.JFrame {

    public static SalesCart cart = new SalesCart();
    public static final String FILE_NAME_Cart = "DataFiles/Cart.txt";
    public static final String FILE_NAME_Product = "DataFiles/Products.txt";
    private SetOfCart cartSet = new SetOfCart();
    private SetOfProducts productSet = new SetOfProducts();

    double qty;
    /**
     * Creates new form cart
     */
    String username, userLevel, email;

    public Cart() {
        initComponents();
    }

    public Cart(String username, String userLevel, String email) {
        initComponents();
        this.username = username;
        this.userLevel = userLevel;
        this.email = email;
logedUser.setText(email);
        if (userLevel.equals("user")) {
            l1.setText("Home");
            l2.setText("Product Sales");
            l3.setText("View Profile");
            l4.setText("Feedbacks");
        } else {
            l1.setText("Field Stations");
            l2.setText("Product Sales");
            l3.setText("Admin Panal");
            l4.setText("Data Analysis");
        }

        try {
            for (SalesCart cart : Serialization.deserializeCart()) {
                if (cart.getEmail().equals(username)) {
                    cartSet.addCart(cart);
                    System.out.println(cart.getCartID());
                }
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            for (ProductsImp productImp : Serialization.deserializeProducts()) {

                productSet.add(productImp);

            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(productObserverImp.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tableload(cartSet);

    }

    /**
     *
     * table load of cart interface
     *
     * @param carts
     */
    private void Tableload(SetOfCart carts) {

        String[] colName = {"Product ID", "Name", "Quantity", "Price"};
        Object[][] object = new Object[carts.size()][4];
        int i = 0;
        if (carts.size() != 0) {
            for (SalesCart cart : carts) {
                object[i][0] = cart.getProductID();
                object[i][1] = cart.getName();
                object[i][2] = cart.getQuantity();
                object[i][3] = cart.getPrice();
                i++;
            }

        }

        DefaultTableModel model = new DefaultTableModel(object, colName) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };

        tblmcCart.setModel(model);
        tblmcCart.setRowSorter(new TableRowSorter<>(model));
        tblmcCart.setAutoscrolls(true);
        tblmcCart.getTableHeader().setReorderingAllowed(false);

        // display sub total for products
        double tot = cartSet.calculateTotal(carts);
        double ship = cartSet.shippingCharge(tot);
        double amount = tot + ship;
        txtsubTot.setText(Double.toString(tot));
        txtShipping.setText(Double.toString(ship));
        total.setText(Double.toString(amount));

    }

    public void clear() {
        productIDtxt.setText("");
        txtsubTot.setText("");
        txtShipping.setText("");
        total.setText("");
        cartSet.removeAll(cartSet);

        try {
            for (SalesCart cart : Serialization.deserializeCart()) {
                if (cart.getEmail().equals(username)) {
                    cartSet.addCart(cart);
                    System.out.println(cart.getCartID());
                }
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tableload(cartSet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        txtancName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tblmcTable = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        txtsubTot = new javax.swing.JTextField();
        txtShipping = new javax.swing.JTextField();
        remove = new javax.swing.JLabel();
        tblmcTable1 = new javax.swing.JLabel();
        productIDtxt = new javax.swing.JTextField();
        btnmcCheckout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmcCart = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        logedUser = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Agriculture Sensoring Sys");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 4, 130, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("www.Agrivi.com/Agriculture Sensoring/productSales.htm");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 31, 540, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 40, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max2.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 40, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("My Cart");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Products");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("My Cart");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 120, -1));

        l1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 102, 102));
        l1.setText("Field Stations");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 150, 30));

        l2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(51, 51, 51));
        l2.setText("Product Sales");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 160, 30));

        l3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(102, 102, 102));
        l3.setText("Admin Panal");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 140, 30));

        l4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 102, 102));
        l4.setText("Data Analysis");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 140, 30));

        txtancName.setEditable(false);
        txtancName.setBackground(new java.awt.Color(255, 255, 255));
        txtancName.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtancName.setForeground(new java.awt.Color(102, 102, 102));
        txtancName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtancName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 620, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 10, 350));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Total Amount          :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Shipping Charges    :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 170, -1));

        tblmcTable.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        tblmcTable.setForeground(new java.awt.Color(102, 102, 102));
        tblmcTable.setText("Sub Total                 :");
        getContentPane().add(tblmcTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 170, -1));

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        total.setForeground(new java.awt.Color(102, 102, 102));
        total.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 180, 30));

        txtsubTot.setEditable(false);
        txtsubTot.setBackground(new java.awt.Color(255, 255, 255));
        txtsubTot.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtsubTot.setForeground(new java.awt.Color(102, 102, 102));
        txtsubTot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtsubTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 180, 30));

        txtShipping.setEditable(false);
        txtShipping.setBackground(new java.awt.Color(255, 255, 255));
        txtShipping.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtShipping.setForeground(new java.awt.Color(102, 102, 102));
        txtShipping.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtShipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 180, 30));

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        remove.setText("jLabel10");
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 60, 40));

        tblmcTable1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        tblmcTable1.setForeground(new java.awt.Color(102, 102, 102));
        tblmcTable1.setText("Product ID               :");
        getContentPane().add(tblmcTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 170, -1));

        productIDtxt.setEditable(false);
        productIDtxt.setBackground(new java.awt.Color(255, 255, 255));
        productIDtxt.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        productIDtxt.setForeground(new java.awt.Color(102, 102, 102));
        productIDtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(productIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 180, 30));

        btnmcCheckout.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        btnmcCheckout.setForeground(new java.awt.Color(102, 102, 102));
        btnmcCheckout.setText("Checkout");
        btnmcCheckout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnmcCheckout.setContentAreaFilled(false);
        btnmcCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmcCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmcCheckoutMouseEntered(evt);
            }
        });
        getContentPane().add(btnmcCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, 130, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tblmcCart.setForeground(new java.awt.Color(153, 153, 153));
        tblmcCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmcCart.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblmcCart.setFillsViewportHeight(true);
        tblmcCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmcCartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblmcCart);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 560, 260));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SemMainLogo.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 480, 160));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footer.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1360, -1));

        logedUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        logedUser.setForeground(new java.awt.Color(102, 102, 102));
        logedUser.setText("logged User");
        getContentPane().add(logedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 50));

        logout1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        logout1.setForeground(new java.awt.Color(102, 102, 102));
        logout1.setText("Log Out");
        logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
        });
        getContentPane().add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 90, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Cart c = new Cart(username, userLevel, email);
        c.setVisible(true);
        this.hide();
        cartSet.removeAll(cartSet);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        ProductSale p = new ProductSale(username, userLevel, email);
        p.setVisible(true);
        this.hide();
        cartSet.removeAll(cartSet);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        if (userLevel.equals("user")) {
            userMain u = new userMain(username, userLevel, email);
            u.setVisible(true);
            this.hide();
            cartSet.removeAll(cartSet);
        } else {
            viewSensorDetails v = new viewSensorDetails(username, userLevel, email);
            v.setVisible(true);
            this.hide();
            cartSet.removeAll(cartSet);
        }
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        ProductSale p = new ProductSale(username, userLevel, email);
        p.setVisible(true);
        this.hide();
        cartSet.removeAll(cartSet);
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        if (userLevel.equals("user")) {
            viewProfile v = new viewProfile(username, userLevel, email);
            v.setVisible(true);
            this.hide();
            cartSet.removeAll(cartSet);
        } else {
            userManagement u = new userManagement(username, userLevel, email);
            u.setVisible(true);
            this.hide();
            cartSet.removeAll(cartSet);
        }
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        if (userLevel.equals("user")) {
            feedback f = new feedback(username, userLevel, email);
            f.setVisible(true);
            this.hide();
            cartSet.removeAll(cartSet);
        } else {
            field_harvest f = new field_harvest(username, userLevel, email);
            f.setVisible(true);
            this.hide();
            cartSet.removeAll(cartSet);
        }
    }//GEN-LAST:event_l4MouseClicked

    private void btnmcCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmcCheckoutMouseClicked
        double Amount = Double.parseDouble(total.getText());
        Checkout s = new Checkout(username, userLevel, email, Amount);
        s.setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnmcCheckoutMouseClicked

    private void tblmcCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmcCartMouseClicked

        DefaultTableModel dtm = (DefaultTableModel) tblmcCart.getModel();

        int row = tblmcCart.getSelectedRow();

        productIDtxt.setText(tblmcCart.getValueAt(row, 0).toString());
        qty = Double.parseDouble(tblmcCart.getValueAt(row, 2).toString());

    }//GEN-LAST:event_tblmcCartMouseClicked

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        int productID;

        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this product?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == 0) {
            if (productIDtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a product to remove from cart...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                productID = Integer.parseInt(productIDtxt.getText());

                for (SalesCart cart : cartSet) {
                    if (cart.getProductID() == productID) {

                        if (cartSet.removeCart(cart)) {
                            try {
                                Serialization.Serialize(cartSet, FILE_NAME_Cart);
                                //Serialization.Serialize(productSet, FILE_NAME_Product);
                                JOptionPane.showMessageDialog(this, "Product removed from the cart Sucsessfully", "Message", JOptionPane.PLAIN_MESSAGE);
                                ProductsImp product = productSet.getProductFromID(productID).elementAt(0);
                                cartSet.updateProductqty(product, qty);

                                clear();
                            } catch (IOException ex) {
                                   JOptionPane.showMessageDialog(this, "Unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                        break;
                    }
                }
            }
        } else {
            clear();
        }
    }//GEN-LAST:event_removeMouseClicked

    private void btnmcCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmcCheckoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmcCheckoutMouseEntered

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        Login l=new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logout1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmcCheckout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel logedUser;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel logout1;
    private javax.swing.JTextField productIDtxt;
    private javax.swing.JLabel remove;
    private javax.swing.JTable tblmcCart;
    private javax.swing.JLabel tblmcTable;
    private javax.swing.JLabel tblmcTable1;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtShipping;
    private javax.swing.JTextField txtancName;
    private javax.swing.JTextField txtsubTot;
    // End of variables declaration//GEN-END:variables
}
