/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.fertilizer.Fertilizer;
import Classes.fertilizer.SetOfFertilizer;
import Classes.serialization.Serialization;
import Validations.validations;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Kasun
 */
public class fertilizerManagement extends javax.swing.JFrame {

    /**
     * Creates new form userManagement
     */
    String username, userLevel;
    public static final String FILE_NAME_Fertilizer = "DataFiles/fertilizer.txt";
    public static SetOfFertilizer theFertilizer = new SetOfFertilizer();
    public static SetOfFertilizer searchFertilizers = new SetOfFertilizer();

    /**
     *
     */
    public fertilizerManagement() {
        initComponents();
    }

    /**
     *
     * @param username
     * @param userLevel
     * @param email
     */
    public fertilizerManagement(String username, String userLevel, String email) {
        initComponents();
        this.username = username;
        this.userLevel = userLevel;
        logedUser.setText(email);

        try {
            for (Fertilizer fertilizer : Serialization.deserializeFertilizer()) {
                theFertilizer.addFertilizer(fertilizer);
                fertilizer.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        TableLoad(jTable1, theFertilizer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        max = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboSensorType = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        qty = new javax.swing.JTextField();
        min = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        txtancName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        crops = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        logedUser = new javax.swing.JLabel();
        logout4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(102, 102, 102));
        ID.setText("0");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 290, 230, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Fertilizer ID          :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 140, 30));

        d.setEditable(false);
        d.setBackground(new java.awt.Color(255, 255, 255));
        d.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        d.setForeground(new java.awt.Color(102, 102, 102));
        d.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 240, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max2.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 40, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 40, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, -1));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Manage Users");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Manage Sensor Details");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 250, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Manage Crop");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 40));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Manage Products ");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 190, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Add Product");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Update Product");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, 40));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 230, 10));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Manage Fields");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 190, 40));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 230, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 10, 350));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Field Stations");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 150, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Crop Sales");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 120, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Admin Panal");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 140, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Quantity              :");
        jLabel19.setToolTipText("");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 140, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Data Analysis");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 140, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("(Quantity in bottels)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 140, 30));

        max.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        max.setForeground(new java.awt.Color(102, 102, 102));
        max.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        max.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxKeyTyped(evt);
            }
        });
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 240, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Min Value           :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 140, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Max Value          :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Sensor Type        :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 30));

        comboSensorType.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboSensorType.setForeground(new java.awt.Color(102, 102, 102));
        comboSensorType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soil Moisture Sensor", "Soil Acidity Sensor", " " }));
        comboSensorType.setBorder(null);
        getContentPane().add(comboSensorType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 240, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Description         :");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 140, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 153));
        jLabel31.setText("Manage Fertilizer");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 190, 40));

        reset.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        reset.setForeground(new java.awt.Color(102, 102, 102));
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reset.setContentAreaFilled(false);
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 630, 120, 30));

        add.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        add.setForeground(new java.awt.Color(102, 102, 102));
        add.setText("Add Fertilizer");
        add.setToolTipText("");
        add.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add.setContentAreaFilled(false);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 120, 30));

        update.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 102));
        update.setText("Update Fertilizer");
        update.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        update.setContentAreaFilled(false);
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 630, 120, 30));

        delete.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        delete.setForeground(new java.awt.Color(102, 102, 102));
        delete.setText("Delete Fertilizer");
        delete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delete.setContentAreaFilled(false);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 630, 140, 30));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SemMainLogo.png"))); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 480, 160));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 230, 10));

        qty.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        qty.setForeground(new java.awt.Color(102, 102, 102));
        qty.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 240, -1));

        min.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        min.setForeground(new java.awt.Color(102, 102, 102));
        min.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minKeyTyped(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 240, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Name                  :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 140, 30));

        Name.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(102, 102, 102));
        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 240, -1));

        txtancName.setEditable(false);
        txtancName.setBackground(new java.awt.Color(255, 255, 255));
        txtancName.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtancName.setForeground(new java.awt.Color(102, 102, 102));
        txtancName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtancName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 590, 40));

        crops.setColumns(15);
        crops.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        crops.setForeground(new java.awt.Color(102, 102, 102));
        crops.setRows(3);
        jScrollPane2.setViewportView(crops);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 240, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Crops                  :");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 150, 30));

        desc.setColumns(15);
        desc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(102, 102, 102));
        desc.setRows(3);
        jScrollPane3.setViewportView(desc);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 596, 240, 80));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 40, 40));

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("(Separate each with \",\")");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 140, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setForeground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setFillsViewportHeight(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 610, 270));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footer.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel34.setText("Agriculture Sensoring Sys");
        jLabel34.setToolTipText("");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 4, 130, 20));

        search1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        search1.setForeground(new java.awt.Color(153, 153, 153));
        search1.setText("Fertilizer Name ...");
        search1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search1MouseClicked(evt);
            }
        });
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        getContentPane().add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 470, 40));

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("www.Agrivi.com/Agriculture Sensoring/adminPanal.htm");
        jLabel35.setToolTipText("");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 31, 540, 20));

        logedUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        logedUser.setForeground(new java.awt.Color(102, 102, 102));
        logedUser.setText("logged User");
        getContentPane().add(logedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 50));

        logout4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        logout4.setForeground(new java.awt.Color(102, 102, 102));
        logout4.setText("Log Out");
        logout4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
        });
        getContentPane().add(logout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 90, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        userManagement a = new userManagement(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        manageSensorDetails m = new manageSensorDetails(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        AddCrop a = new AddCrop(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        AddNewProduct a = new AddNewProduct(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        ProductStock p = new ProductStock(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();

        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        manage_farm m = new manage_farm(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        fertilizerManagement f = new fertilizerManagement(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
        theFertilizer.removeAll(theFertilizer);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        // when user click on tbInfo table, all the information what in user selected row will want to show on Update tab
        //  load info to update tab
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        int row = jTable1.getSelectedRow();

        ID.setText(jTable1.getValueAt(row, 0).toString());
        Name.setText(jTable1.getValueAt(row, 1).toString());
        comboSensorType.setSelectedItem(jTable1.getValueAt(row, 2).toString());
        crops.setText(jTable1.getValueAt(row, 3).toString());
        min.setText(jTable1.getValueAt(row, 4).toString());
        max.setText(jTable1.getValueAt(row, 5).toString());
        qty.setText(jTable1.getValueAt(row, 6).toString());
        desc.setText(jTable1.getValueAt(row, 7).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    //add fertilizer
    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        String name, SensorType, crop, description;
        double minValue, maxValue;
        int quantity;

        if (Name.getText().isEmpty() || crops.getText().isEmpty() || min.getText().isEmpty()
                || max.getText().isEmpty() || qty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide all the necessary details...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            name = Name.getText();
            SensorType = comboSensorType.getSelectedItem().toString();
            crop = crops.getText();
            minValue = Double.parseDouble(min.getText());
            maxValue = Double.parseDouble(max.getText());
            quantity = Integer.parseInt(qty.getText());
            description = desc.getText();

            String status = addFertilizer(name, SensorType, crop, description, minValue, maxValue, quantity);
            if (status.equals("success")) {
                JOptionPane.showMessageDialog(this, "You have added the new fertilizer successfully", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                clear();

                TableLoad(jTable1, theFertilizer);

            } else {
                JOptionPane.showMessageDialog(this, "Adding fertilizer unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addMouseClicked

    /**
     *
     * @param Name
     * @param SensorType
     * @param crops
     * @param description
     * @param minValue
     * @param maxValue
     * @param quantity
     * @return
     */
    public String addFertilizer(String Name, String SensorType, String crops, String description, double minValue, double maxValue, int quantity) {
        String status = "";

        new Fertilizer.SingletonBuilder(Name, SensorType, crops, quantity, minValue, maxValue).description(description).build();

        theFertilizer.addFertilizer(Fertilizer.getInstance());
        try {
            Serialization.Serialize(theFertilizer, FILE_NAME_Fertilizer);
            status = "success";
        } catch (Exception ex) {
            status = "fail";
            System.out.println(ex.getMessage());
        }

        return status;
    }

    private void search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseClicked
        search1.setText("");
    }//GEN-LAST:event_search1MouseClicked

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
        if (!search1.getText().equalsIgnoreCase("")) {
            searchFertilizers = theFertilizer.getFertilizerFromName(search1.getText());
            TableLoad(jTable1, searchFertilizers);

        }
    }//GEN-LAST:event_search1KeyReleased

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        clear();
    }//GEN-LAST:event_resetMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        String name, SensorType, crop, description;
        double minValue, maxValue;
        int quantity;

        if (Name.getText().isEmpty() || crops.getText().isEmpty() || min.getText().isEmpty()
                || max.getText().isEmpty() || qty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide all the necessary details...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            name = Name.getText();
            SensorType = comboSensorType.getSelectedItem().toString();
            crop = crops.getText();
            minValue = Double.parseDouble(min.getText());
            maxValue = Double.parseDouble(max.getText());
            quantity = Integer.parseInt(qty.getText());
            description = desc.getText();

            Fertilizer fertilizer = theFertilizer.getFertilizerFromNumber(Integer.parseInt(ID.getText())).firstElement();
            String status = theFertilizer.updatedetails(fertilizer, name, SensorType, crop, description, minValue, maxValue, quantity);
            if (status.equals("success")) {
                try {
                    JOptionPane.showMessageDialog(this, "You have updated successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                    Serialization.Serialize(theFertilizer, FILE_NAME_Fertilizer);
                    clear();
                    TableLoad(jTable1, theFertilizer);
                } catch (IOException ex) {
                    Logger.getLogger(fertilizerManagement.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Update unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int fertilizerNum;
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this fertilizer?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            if (ID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a fertilizer to delete...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                fertilizerNum = Integer.parseInt(ID.getText());

                Fertilizer fertilizer = theFertilizer.getFertilizerFromNumber(Integer.parseInt(ID.getText())).firstElement();
                boolean status = theFertilizer.removeFertilizer(fertilizer);
                if (status) {
                    try {
                        Serialization.Serialize(theFertilizer, FILE_NAME_Fertilizer);
                        JOptionPane.showMessageDialog(this, "You have deleted successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                        clear();
                        TableLoad(jTable1, theFertilizer);
                    } catch (IOException ex) {
                        Logger.getLogger(fertilizerManagement.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void minKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minKeyTyped
        validations.validateNumber(min, evt);
    }//GEN-LAST:event_minKeyTyped

    private void maxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxKeyTyped
        validations.validateNumber(max, evt);
    }//GEN-LAST:event_maxKeyTyped

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        validations.validateNumber(qty, evt);
    }//GEN-LAST:event_qtyKeyTyped

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        Login l=new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logout4MouseClicked

    /**
     *
     */
    public void clear() {
        ID.setText("");
        comboSensorType.setSelectedItem("Soil Moisture Sensor");
        Name.setText("");
        crops.setText("");
        qty.setText("");
        min.setText("");
        max.setText("");
        desc.setText("");
        search1.setText("");

        theFertilizer.removeAll(theFertilizer);
        try {
            for (Fertilizer fertilizer : Serialization.deserializeFertilizer()) {
                theFertilizer.addFertilizer(fertilizer);
                fertilizer.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    //display table load
    /**
     *
     * @param table
     * @param searchList
     */
    public void TableLoad(JTable table, SetOfFertilizer searchList) {
        String[] colName = {"ID", "Name", "Sensor Type", "Crops", "Min", "Max", "Qty.", "Description"};
        Object[][] object = new Object[searchList.size()][8];
        int i = 0;
        if (searchList.size() != 0) {
            for (Fertilizer fertilizer : searchList) {
                object[i][0] = fertilizer.getFertilizerNumber();
                object[i][1] = fertilizer.getName();
                object[i][2] = fertilizer.getSensorType();
                object[i][3] = fertilizer.getCrops();
                object[i][4] = fertilizer.getMinValue();
                object[i][5] = fertilizer.getMaxValue();
                object[i][6] = fertilizer.getQuntity();
                object[i][7] = fertilizer.getDescription();

                i++;

            }
        }

        DefaultTableModel model = new DefaultTableModel(object, colName) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        table.setModel(model);
        table.setRowSorter(new TableRowSorter<TableModel>(model));
        table.setAutoscrolls(true);
        table.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fertilizerManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JTextField Name;
    private javax.swing.JButton add;
    private javax.swing.JComboBox comboSensorType;
    private javax.swing.JTextArea crops;
    private javax.swing.JTextField d;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logedUser;
    private javax.swing.JLabel logout4;
    private javax.swing.JTextField max;
    private javax.swing.JTextField min;
    private javax.swing.JTextField qty;
    private javax.swing.JButton reset;
    private javax.swing.JTextField search1;
    private javax.swing.JTextField txtancName;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
