/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.analysis.Analiser;
import Classes.analysis.CropAnalyser;
import Classes.analysis.PriceDecorator;
import Classes.analysis.QuantityDecorator;
import Classes.farm.SetOfFarm;
import Classes.farm.farms;
import Classes.serialization.Serialization;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author gihan
 */
public class field_harvest extends javax.swing.JFrame {

    /**
     * Creates new form field_harvest
     */
    String username, userLevel;
    public static SetOfFarm thefarms = new SetOfFarm();
    SimpleDateFormat sdf = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy");
    Calendar cal = Calendar.getInstance();

    /**
     *
     */
    public field_harvest() {
        initComponents();
    }

    /**
     *
     * @param username
     * @param userLevel
     * @param email
     */
    public field_harvest(String username, String userLevel, String email) {
        initComponents();
        this.username = username;
        this.userLevel = userLevel;
        logedUser.setText(email);

        startDate.getMonthView().setUpperBound(Calendar.getInstance().getTime());
        endDate.getMonthView().setUpperBound(Calendar.getInstance().getTime());
        cal.add(Calendar.DATE, -1);
        startDate.setDate(cal.getTime());
        endDate.setDate(Calendar.getInstance().getTime());

        try {
            for (farms farm : Serialization.deserializeFarm()) {
                thefarms.addfarm(farm);
                farm.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        String values = "";

        for (int i = 0; i < thefarms.size(); i++) {
            values = values + " " + thefarms.elementAt(i).getfarmNumber();
        }

        String[] splited = values.split("\\s+");
        for (int i = 0; i < splited.length; i++) {
            System.out.println(splited[i]);
        }
        loadCombo(jComboBox1, splited);
    }

    /**
     *
     * @param fieldID
     * @param start
     * @param end
     * @return
     */
    public String getAnalysis(String type, int fieldID, Date start, Date end) {

        String analiseDetails = "";
        if (type.equals("quantity") || type.equals("")) {
            Analiser analyser = new QuantityDecorator(new CropAnalyser());
            analiseDetails = analyser.analiseDetails("crop", fieldID, start, end);
            System.out.println(analiseDetails);
        } else {
            Analiser analyser = new PriceDecorator(new CropAnalyser());
            analiseDetails = analyser.analiseDetails("crop", fieldID, start, end);
            System.out.println(analiseDetails);
        }
        return analiseDetails;
    }

    /**
     *
     * @param values
     * @param jComboBox
     */
    public void loadCombo(JComboBox jComboBox, String[] values) {
        jComboBox.removeAllItems();
        jComboBox.addItem("Select a Farm");
        for (int i = 1; i < values.length; i++) {
            jComboBox.addItem(values[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        rdYes = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        endDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        SM = new javax.swing.JTextField();
        ST = new javax.swing.JTextField();
        AT = new javax.swing.JTextField();
        SA = new javax.swing.JTextField();
        LS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        totalOfID = new javax.swing.JTextField();
        txtancDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        precentage = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        startDate = new org.jdesktop.swingx.JXDatePicker();
        cc1 = new javax.swing.JTextField();
        rdno = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtancName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        logedUser = new javax.swing.JLabel();
        logout4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Start Date         :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 130, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox1.setBorder(null);
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 520, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Field harvest details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 230, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max2.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 40, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 40, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Crop Details Analysis");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 40));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SemMainLogo.png"))); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 480, 160));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 10, 350));

        l1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 102, 102));
        l1.setText("Field Stations");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 150, 30));

        l2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 102, 102));
        l2.setText("Product Sales");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 150, 30));

        l3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(102, 102, 102));
        l3.setText("Admin Panal");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 140, 30));

        l4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        l4.setForeground(new java.awt.Color(51, 51, 51));
        l4.setText("Data Analysis");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 170, 30));

        rdYes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdYes);
        rdYes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        rdYes.setForeground(new java.awt.Color(102, 102, 102));
        rdYes.setSelected(true);
        rdYes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdYesStateChanged(evt);
            }
        });
        getContentPane().add(rdYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 30, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Select field        :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("End Date         :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 130, -1));

        endDate.setForeground(new java.awt.Color(102, 102, 102));
        endDate.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        endDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateActionPerformed(evt);
            }
        });
        getContentPane().add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Average Details");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 150, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Average soil moisture sensors          :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 290, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Average soiltemperature sensors     :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 290, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Average Air tempurature sensors     :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 290, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Aaverage soil acidity                        :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 290, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Average Lights                                 :");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 290, -1));

        SM.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        SM.setForeground(new java.awt.Color(102, 102, 102));
        SM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(SM, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 220, -1));

        ST.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ST.setForeground(new java.awt.Color(102, 102, 102));
        ST.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 220, -1));

        AT.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        AT.setForeground(new java.awt.Color(102, 102, 102));
        AT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 220, -1));

        SA.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        SA.setForeground(new java.awt.Color(102, 102, 102));
        SA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(SA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 220, -1));

        LS.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LS.setForeground(new java.awt.Color(102, 102, 102));
        LS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(LS, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Total  Quantity                   :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 220, -1));

        total.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(102, 102, 102));
        total.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 450, 220, -1));

        totalOfID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        totalOfID.setForeground(new java.awt.Color(102, 102, 102));
        totalOfID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(totalOfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 500, 220, -1));

        txtancDescription.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtancDescription.setForeground(new java.awt.Color(102, 102, 102));
        txtancDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtancDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 570, 170));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Average  Quantity              :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 220, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Presentage of Quantity      :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 230, -1));

        precentage.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        precentage.setForeground(new java.awt.Color(102, 102, 102));
        precentage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(precentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 550, 220, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Quantity");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 70, -1));

        startDate.setForeground(new java.awt.Color(102, 102, 102));
        startDate.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        startDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateActionPerformed(evt);
            }
        });
        getContentPane().add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 180, -1));

        cc1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cc1.setForeground(new java.awt.Color(102, 102, 102));
        cc1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, 120, 40));

        rdno.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdno);
        rdno.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        rdno.setForeground(new java.awt.Color(102, 102, 102));
        rdno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdnoStateChanged(evt);
            }
        });
        getContentPane().add(rdno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 390, 70, -1));

        cc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cc.setForeground(new java.awt.Color(102, 102, 102));
        cc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, 120, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footer.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Product Details Analysis");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 10));

        txtancName.setEditable(false);
        txtancName.setBackground(new java.awt.Color(255, 255, 255));
        txtancName.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtancName.setForeground(new java.awt.Color(102, 102, 102));
        txtancName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtancName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 660, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Agriculture Sensoring Sys");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 4, 130, 20));

        logedUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        logedUser.setForeground(new java.awt.Color(102, 102, 102));
        logedUser.setText("logged User");
        getContentPane().add(logedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 50));

        logout4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        logout4.setForeground(new java.awt.Color(102, 102, 102));
        logout4.setText("Log Out");
        logout4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
        });
        getContentPane().add(logout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 90, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("www.Agrivi.com/Agriculture Sensoring/dataAnalysis.htm");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 31, 540, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        field_harvest f = new field_harvest(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        viewSensorDetails v = new viewSensorDetails(username, userLevel, logedUser.getText());
        v.setVisible(true);
        this.hide();
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        ProductSale p = new ProductSale(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        userManagement u = new userManagement(username, userLevel, logedUser.getText());
        u.setVisible(true);
        this.hide();
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        field_harvest f = new field_harvest(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
    }//GEN-LAST:event_l4MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        productAnalysis p = new productAnalysis(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

        process();

    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     *
     */
    private void process() {
        if (!jComboBox1.getSelectedItem().toString().equals("Select a Farm")) {
            String details, radio = "";
            if (rdYes.isSelected()) {
                radio = "quantity";
                details = getAnalysis(radio, Integer.parseInt(jComboBox1.getSelectedItem().toString()), startDate.getDate(), endDate.getDate());
                String[] count = details.split("Quntity");
                String[] averageSens = count[0].split(" ");
                AT.setText((double)Math.round((Double.parseDouble(averageSens[0]) * 100.0) / 100.0) + "");
                LS.setText((double)Math.round((Double.parseDouble(averageSens[1]) * 100.0) / 100.0) + "");
                SA.setText((double)Math.round((Double.parseDouble(averageSens[2]) * 100.0) / 100.0) + "");
                SM.setText((double)Math.round((Double.parseDouble(averageSens[3]) * 100.0) / 100.0) + "");
                ST.setText((double)Math.round((Double.parseDouble(averageSens[4]) * 100.0) / 100.0) + "");

                String[] tot = count[1].split(" ");
                total.setText(tot[0]);
                totalOfID.setText(tot[1]);
                precentage.setText(tot[2]);

                jLabel3.setText("Total  Quantity                   :");
                jLabel2.setText("Average  Quantity              :");
                jLabel20.setText("Presentage of Quantity         :");

            } else if (rdno.isSelected()) {
                radio = "price";
                details = getAnalysis(radio, Integer.parseInt(jComboBox1.getSelectedItem().toString()), startDate.getDate(), endDate.getDate());
                String[] count = details.split("price");
                String[] averageSens = count[0].split(" ");
                AT.setText((double)Math.round((Double.parseDouble(averageSens[0]) * 100.0) / 100.0) + "");
                LS.setText((double)Math.round((Double.parseDouble(averageSens[1]) * 100.0) / 100.0) + "");
                SA.setText((double)Math.round((Double.parseDouble(averageSens[2]) * 100.0) / 100.0) + "");
                SM.setText((double)Math.round((Double.parseDouble(averageSens[3]) * 100.0) / 100.0) + "");
                ST.setText((double)Math.round((Double.parseDouble(averageSens[4]) * 100.0) / 100.0) + "");

                jLabel3.setText("Total Average Price           :");
                jLabel2.setText("Average Price of Crop         :");
                jLabel20.setText("Percentage of Average Price :");

                String[] tot = count[1].split(" ");
                total.setText(tot[0]);
                totalOfID.setText(tot[1]);
                precentage.setText(tot[2]);
            }

        } else {
            AT.setText("");
            LS.setText("");
            SA.setText("");
            SM.setText("");
            ST.setText("");
            total.setText("");
            totalOfID.setText("");
            precentage.setText("");

        }
    }
    private void endDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateActionPerformed
        if (endDate.getEditor().getText().isEmpty()) {
            endDate.setDate(Calendar.getInstance().getTime());
        }
        process();
    }//GEN-LAST:event_endDateActionPerformed

    private void startDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateActionPerformed
        if (startDate.getEditor().getText().isEmpty()) {
            cal.add(Calendar.DATE, -1);
            startDate.setDate(cal.getTime());
        }
        System.out.println(sdf.format(startDate.getDate()));
        process();
    }//GEN-LAST:event_startDateActionPerformed

    private void rdYesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdYesStateChanged
        process();
    }//GEN-LAST:event_rdYesStateChanged

    private void rdnoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdnoStateChanged
        process();
    }//GEN-LAST:event_rdnoStateChanged

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        Login l=new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logout4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(field_harvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new field_harvest().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AT;
    private javax.swing.JTextField LS;
    private javax.swing.JTextField SA;
    private javax.swing.JTextField SM;
    private javax.swing.JTextField ST;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cc;
    private javax.swing.JTextField cc1;
    private org.jdesktop.swingx.JXDatePicker endDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel logedUser;
    private javax.swing.JLabel logout4;
    private javax.swing.JTextField precentage;
    private javax.swing.JRadioButton rdYes;
    private javax.swing.JRadioButton rdno;
    private org.jdesktop.swingx.JXDatePicker startDate;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalOfID;
    private javax.swing.JTextField txtancDescription;
    private javax.swing.JTextField txtancName;
    // End of variables declaration//GEN-END:variables
}
