/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.serialization.Serialization;
import Classes.user.SendEmail;
import Classes.user.SetOfRandomCode;
import Classes.user.SetOfUsers;
import Classes.user.User;
import Classes.user.randomCode;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun
 */
public class Forgot_password extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_password
     */
    public static SetOfUsers searchUsers = new SetOfUsers();
    public static final String FILE_NAME_Users = "DataFiles/Users.txt";

    public static SetOfRandomCode searchCode = new SetOfRandomCode();
    public static final String FILE_NAME_RandomCodes = "DataFiles/RandomCodes.txt";

    /**
     *
     */
    public Forgot_password() {
        initComponents();
        try {
            for (User member : Serialization.deserializeUsers()) {
                searchUsers.addUser(member);
                member.print();
            }

            for (randomCode code : Serialization.deserializeRandomCode()) {
                searchCode.addCode(code);
                code.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtsenderEmail = new javax.swing.JTextField();
        txtVerificationCode1 = new javax.swing.JTextField();
        btnancSave = new javax.swing.JButton();
        btnancSave1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 40, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max2.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 40, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Agriculture Sensoring Sys");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 4, 130, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("www.Agrivi.com/Agriculture Sensoring/ForgetPassword.htm");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 31, 540, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Having trouble signing in");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 380, 60));
        jLabel4.getAccessibleContext().setAccessibleName("");

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 33, 20, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Resend Code");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Enter email address  :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 180, -1));

        txtsenderEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtsenderEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtsenderEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtsenderEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 290, 30));

        txtVerificationCode1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtVerificationCode1.setForeground(new java.awt.Color(102, 102, 102));
        txtVerificationCode1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtVerificationCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 290, 30));

        btnancSave.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        btnancSave.setForeground(new java.awt.Color(102, 102, 102));
        btnancSave.setText("Send");
        btnancSave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnancSave.setContentAreaFilled(false);
        btnancSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnancSaveMouseClicked(evt);
            }
        });
        getContentPane().add(btnancSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 120, 30));

        btnancSave1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        btnancSave1.setForeground(new java.awt.Color(102, 102, 102));
        btnancSave1.setText("Ok");
        btnancSave1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnancSave1.setContentAreaFilled(false);
        btnancSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnancSave1MouseClicked(evt);
            }
        });
        getContentPane().add(btnancSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 120, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Verification code      :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("We have send a verification code to your email.....");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 570, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footer.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainLogo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new Login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnancSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnancSaveMouseClicked

        if (txtsenderEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide the email address...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            String status = "";

            for (User user : searchUsers) {
                if (user.getUsername().equals(txtsenderEmail.getText())) {
                    status = "true";
                    break;
                } else {
                    status = "false";
                }
            }

            if (status == "true") {
                String stat = sendMessage(txtsenderEmail.getText());
                if (stat == "success") {
                    JOptionPane.showMessageDialog(this, "Varification Code has been send to your email...\n"
                            + " Please type the code below to reset your password ", "Next Step", JOptionPane.INFORMATION_MESSAGE);
                    searchCode.removeAll(searchCode);
                    try {
                        for (randomCode code : Serialization.deserializeRandomCode()) {
                            searchCode.addCode(code);
                            code.print();
                        }
                    } catch (IOException | ClassNotFoundException ex) {
                        Logger.getLogger(Forgot_password.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Seems to be a internet connection error.. try again later... ", "Error", JOptionPane.ERROR_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(this, "Please Register to the system...", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnancSaveMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        if (txtsenderEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide the email address...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            String status = "";

            for (User user : searchUsers) {
                if (user.getUsername().equals(txtsenderEmail.getText())) {
                    status = "true";
                    break;
                } else {
                    status = "false";
                }
            }

            if (status == "true") {
                String stat = sendMessage(txtsenderEmail.getText());
                if (stat == "success") {
                    JOptionPane.showMessageDialog(this, "Varification Code has been send to your email...\n"
                            + " Please type the code below to reset your password ", "Next Step", JOptionPane.INFORMATION_MESSAGE);
                    searchCode.removeAll(searchCode);
                    try {
                        for (randomCode code : Serialization.deserializeRandomCode()) {
                            searchCode.addCode(code);
                            code.print();
                        }
                    } catch (IOException | ClassNotFoundException ex) {
                        Logger.getLogger(Forgot_password.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Seems to be a internet connection error.. try again later... ", "Error", JOptionPane.ERROR_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(this, "Please Register to the system...", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jLabel9MouseClicked

    //validate Code
    private void btnancSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnancSave1MouseClicked

        String status = validateCode(txtsenderEmail.getText(), txtVerificationCode1.getText());
        if (status == "success") {
            resetPassword r = new resetPassword(txtsenderEmail.getText());
            r.setVisible(true);
            searchCode.removeAll(searchCode);
            txtsenderEmail.setText("");
            txtVerificationCode1.setText("");
            this.hide();

        } else {
            JOptionPane.showMessageDialog(this, "Varification code not match...", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnancSave1MouseClicked

    /**
     *
     * @param email
     * @param code
     * @return
     */
    public static String validateCode(String email, String code) {
        String status = "";
        for (randomCode random : searchCode) {

            if (random.getEmail().equals(email) && random.getRandomCode().equals(code)) {
                status = "success";
                searchCode.removeCode(random);
                try {
                    Serialization.Serialize(searchCode, FILE_NAME_RandomCodes);
                } catch (IOException ex) {
                    Logger.getLogger(userManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            } else {
                status = "error";

            }
        }

        return status;
    }

    //auto genarate randdoom code
    /**
     *
     * @return
     */
    public static String getAlphaNumbericRandom() {
        String chars = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

        int numberOfCodes = 0;
        String code = "";
        while (numberOfCodes < 7) {
            char c = chars.charAt((int) (Math.random() * chars.length()));
            code += c;
            numberOfCodes++;
        }
        return code;
    }

    /**
     *
     * @param email
     * @return
     */
    public static String sendMessage(String email) {
        String verifyCode = getAlphaNumbericRandom();
        String status = "";
        try {
            SendEmail mailSender;
            mailSender = new SendEmail(email, "Verification Message", "Your Verification Code is : " + verifyCode);

            new randomCode.SingletonBuilder(email, verifyCode).build();
            searchCode.addCode(randomCode.getInstance());
            try {
                Serialization.Serialize(searchCode, FILE_NAME_RandomCodes);
                status = "success";
            } catch (Exception ex) {
                status = "fail";
                System.out.println(ex.getMessage());
            }

        } catch (Exception ex) {
            status = "error";
        }
        return status;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnancSave;
    private javax.swing.JButton btnancSave1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtVerificationCode1;
    private javax.swing.JTextField txtsenderEmail;
    // End of variables declaration//GEN-END:variables
}
