/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.farm.SetOfFarm;
import Classes.farm.farms;
import Classes.sensors.Air_Temperature;
import Classes.sensors.Lights_Sensor;
import Classes.sensors.SetOfSensors;
import Classes.sensors.Soil_Acidity;
import Classes.sensors.Soil_Moisture;
import Classes.sensors.Soil_Temperature;
import Classes.sensors.sensorDetails;
import Classes.serialization.Serialization;
import Validations.validations;
import java.awt.HeadlessException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Sachi
 */
public class manageSensorDetails extends javax.swing.JFrame {

    /**
     * Creates new form manageSensorDetails
     */
    String username, userLevel;
    public static SetOfFarm thefarms = new SetOfFarm();
    public static SetOfSensors theSensors = new SetOfSensors();
    public static SetOfSensors searchSensors = new SetOfSensors();
    public static final String FILE_NAME_Sensors = "DataFiles/Sensors.txt";
    public static final String Soil_Moisture = "Soil Moisture Sensor";
    public static final String Soil_Temperature = "Soil Temperature Sensor";
    public static final String Air_Temperature = "Air Temperature Sensor";
    public static final String Soil_Acidity = "Soil Acidity Sensor";
    public static final String Lights_Sensor = "Lights Sensor";
    public static final String FILE_NAME_farms = "DataFiles/farms.txt";

    /**
     *
     */
    public manageSensorDetails() {
        initComponents();
    }

    /**
     *
     * @param username
     * @param userLevel
     * @param email
     */
    public manageSensorDetails(String username, String userLevel, String email) {
        initComponents();
        this.username = username;
        this.userLevel = userLevel;
        logedUser.setText(email);

        try {
            for (farms farm : Serialization.deserializeFarm()) {
                thefarms.addfarm(farm);
                farm.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            for (sensorDetails sensorDetails : Serialization.deserializeSensors()) {
                theSensors.addSensorDetails(sensorDetails);
                sensorDetails.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        String values = "";

        for (farms farm : thefarms) {
            if (!values.contains(farm.getlocation())) {
                values = values + " " + farm.getlocation();
            }
        }
        String[] splited = values.split("\\s+");
        for (int i = 0; i < splited.length; i++) {
            System.out.println(splited[i]);
        }
        loadCombo(comboLocation, splited);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboLocation = new javax.swing.JComboBox();
        comboFarmer = new javax.swing.JComboBox();
        comboFieldID = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sms = new javax.swing.JTextField();
        sts = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ats = new javax.swing.JTextField();
        ls = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        sas = new javax.swing.JTextField();
        txtancName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        CropType = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        logedUser = new javax.swing.JLabel();
        logout4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Field Stations");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Product Sales");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Admin Panal");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Data Analysis");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 140, 30));

        comboLocation.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboLocation.setForeground(new java.awt.Color(102, 102, 102));
        comboLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "London", "Item 2", "Item 3", "Item 4" }));
        comboLocation.setBorder(null);
        comboLocation.setOpaque(false);
        comboLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboLocationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboLocationMouseEntered(evt);
            }
        });
        getContentPane().add(comboLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 350, 240, -1));

        comboFarmer.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboFarmer.setForeground(new java.awt.Color(102, 102, 102));
        comboFarmer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an option" }));
        comboFarmer.setBorder(null);
        comboFarmer.setOpaque(false);
        comboFarmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboFarmerMouseEntered(evt);
            }
        });
        comboFarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFarmerActionPerformed(evt);
            }
        });
        getContentPane().add(comboFarmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 390, 240, -1));

        comboFieldID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboFieldID.setForeground(new java.awt.Color(102, 102, 102));
        comboFieldID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an option" }));
        comboFieldID.setBorder(null);
        comboFieldID.setOpaque(false);
        comboFieldID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboFieldIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboFieldIDMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboFieldIDMouseReleased(evt);
            }
        });
        getContentPane().add(comboFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 430, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Location               :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 150, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Farmer Name       :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, 150, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Crop Type             :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Manage Users");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Manage Sensor Details");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Sensor Details");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 210, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Soil Moisture Sensor (%)         :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 240, 30));

        sms.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sms.setForeground(new java.awt.Color(102, 102, 102));
        sms.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                smsKeyTyped(evt);
            }
        });
        getContentPane().add(sms, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 240, -1));

        sts.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sts.setForeground(new java.awt.Color(102, 102, 102));
        sts.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stsKeyTyped(evt);
            }
        });
        getContentPane().add(sts, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 240, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Soil Temperature Sensor (RH) :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 240, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Air Temperature Sensor (°C)  :");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 230, 30));

        ats.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ats.setForeground(new java.awt.Color(102, 102, 102));
        ats.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                atsKeyTyped(evt);
            }
        });
        getContentPane().add(ats, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 240, -1));

        ls.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ls.setForeground(new java.awt.Color(102, 102, 102));
        ls.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ls.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lsKeyTyped(evt);
            }
        });
        getContentPane().add(ls, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 240, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Lights Sensor (W/m²)             :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 230, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Soil Acidity Sensor (pH)          :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 230, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 10, 350));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        add.setForeground(new java.awt.Color(102, 102, 102));
        add.setText("Add Details");
        add.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add.setContentAreaFilled(false);
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 120, 40));

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        reset.setForeground(new java.awt.Color(102, 102, 102));
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reset.setContentAreaFilled(false);
        reset.setOpaque(true);
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 110, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, -1));

        sas.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sas.setForeground(new java.awt.Color(102, 102, 102));
        sas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sasKeyTyped(evt);
            }
        });
        getContentPane().add(sas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 240, -1));

        txtancName.setEditable(false);
        txtancName.setBackground(new java.awt.Color(255, 255, 255));
        txtancName.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtancName.setForeground(new java.awt.Color(102, 102, 102));
        txtancName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtancName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 660, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SemMainLogo.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 480, 150));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max2.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 40, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Manage Crop");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 40));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 230, 10));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Manage Fields");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 190, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 40, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Manage Products ");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 190, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Add Product");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Update Product");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, 40));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 230, 10));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, 10));

        CropType.setEditable(false);
        CropType.setBackground(new java.awt.Color(255, 255, 255));
        CropType.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        CropType.setForeground(new java.awt.Color(102, 102, 102));
        CropType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(CropType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 240, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Manage Fertilizer");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 190, 40));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 230, 10));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footer.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel23.setText("Agriculture Sensoring Sys");
        jLabel23.setToolTipText("");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 4, 130, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Field ID                 :");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 150, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("www.Agrivi.com/Agriculture Sensoring/adminPanal.htm");
        jLabel28.setToolTipText("");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 31, 540, 20));

        logedUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        logedUser.setForeground(new java.awt.Color(102, 102, 102));
        logedUser.setText("logged User");
        getContentPane().add(logedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 50));

        logout4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        logout4.setForeground(new java.awt.Color(102, 102, 102));
        logout4.setText("Log Out");
        logout4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
        });
        getContentPane().add(logout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 90, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        userManagement a = new userManagement(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        manageSensorDetails m = new manageSensorDetails(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        AddCrop a = new AddCrop(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        manage_farm m = new manage_farm(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        AddNewProduct a = new AddNewProduct(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        ProductStock p = new ProductStock(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();

        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        fertilizerManagement f = new fertilizerManagement(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        viewSensorDetails v = new viewSensorDetails(username, userLevel, logedUser.getText());
        v.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        ProductSale p = new ProductSale(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        manageSensorDetails m = new manageSensorDetails(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        field_harvest f = new field_harvest(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
        theSensors.removeAll(theSensors);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

        if (comboFieldID.getSelectedItem().toString().equals("Select an option") || comboFarmer.getSelectedItem().toString().equals("Select an option")
                || comboLocation.getSelectedItem().toString().equals("Select an option") || CropType.getText().isEmpty() || sms.getText().trim().isEmpty()
                || sts.getText().trim().isEmpty() || ats.getText().trim().isEmpty() || sas.getText().trim().isEmpty()
                || ls.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Provide all the necessary Details", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            for (sensorDetails sensor : theSensors) {
                if (sensor.getfieldID().equals(comboFieldID.getSelectedItem().toString())) {
                    searchSensors.addSensorDetails(sensor);
                    sensor.print();
                }

            }

            if (searchSensors.size() > 0) {

                DateFormat format = new SimpleDateFormat("EEE MMM d HH:mm:ss Z yyyy");
                long MAX_DURATION = 3 * 60 * 1000;//to get the maximum duration of 3 min.
                try {
                    sensorDetails sensor = searchSensors.elementAt(searchSensors.size() - 1);
                    System.out.println(sensor.getDate());
                    Calendar previous = Calendar.getInstance();
                    previous.setTime(format.parse(sensor.getDate()));
                    Calendar now = Calendar.getInstance();

                    long duration = now.getTimeInMillis() - previous.getTimeInMillis();

                    if (duration >= MAX_DURATION) {

                        getDetails();
                    } else {
                        JOptionPane.showMessageDialog(this, "Please try again after 3 minutes", "Error", JOptionPane.ERROR_MESSAGE);
                        clear();
                    }
                } catch (Exception ex) {

                }

            } else {
                getDetails();
            }

        }

    }//GEN-LAST:event_addMouseClicked

    public void getDetails() {
        double SoilMoisture, SoilTemperature, AirTemperature, SoilAcidity, Lights_Sensor;
        String fieldID = comboFieldID.getSelectedItem().toString();
        String crop = CropType.getText();
        SoilMoisture = Double.parseDouble(sms.getText().trim());
        SoilTemperature = Double.parseDouble(sts.getText().trim());
        AirTemperature = Double.parseDouble(ats.getText().trim());
        SoilAcidity = Double.parseDouble(sas.getText().trim());
        Lights_Sensor = Double.parseDouble(ls.getText().trim());
        String status = addDetails(fieldID, crop, SoilMoisture, SoilTemperature, AirTemperature, SoilAcidity, Lights_Sensor);
        if (status == "success") {
            clear();
        }
    }
    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        clear();
    }//GEN-LAST:event_resetMouseClicked

    private void comboFarmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFarmerActionPerformed

    }//GEN-LAST:event_comboFarmerActionPerformed

    private void comboLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboLocationMouseClicked
        String values = "a\nb\n";

        for (farms farm : thefarms) {
            if (farm.getlocation().equals(comboLocation.getSelectedItem().toString()) && !values.contains(farm.getfarmername())) {
                values = values + "\n" + farm.getfarmername();
            }
        }
        String[] splited = values.split("\\n+");
        for (int i = 0; i < splited.length; i++) {
            System.out.println(splited[i]);
        }
        loadCombo(comboFarmer, splited);
    }//GEN-LAST:event_comboLocationMouseClicked

    private void comboLocationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboLocationMouseEntered

    }//GEN-LAST:event_comboLocationMouseEntered

    private void comboFarmerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboFarmerMouseEntered

    }//GEN-LAST:event_comboFarmerMouseEntered

    private void comboFieldIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboFieldIDMouseEntered

    }//GEN-LAST:event_comboFieldIDMouseEntered

    private void comboFieldIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboFieldIDMouseClicked
        String values = "\na\n";

        for (farms farm : thefarms) {

            if (farm.getlocation().equals(comboLocation.getSelectedItem().toString()) && farm.getfarmername().equals(comboFarmer.getSelectedItem().toString()) && !values.contains("" + farm.getfarmNumber())) {
                values = values + "\n" + farm.getfarmNumber();
            }
        }
        String[] splited = values.split("\\n+");
        for (int i = 0; i < splited.length; i++) {
            System.out.println(splited[i]);
        }
        loadCombo(comboFieldID, splited);
    }//GEN-LAST:event_comboFieldIDMouseClicked

    private void comboFieldIDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboFieldIDMouseReleased
        String values = "";

        for (farms farm : thefarms) {
            String num = "" + farm.getfarmNumber();
            if (num.equals("" + comboFieldID.getSelectedItem().toString()) && !values.contains(farm.getfarmtype())) {
                values = values + farm.getfarmtype();
            }
        }
        CropType.setText(values);
        System.out.print(values);
    }//GEN-LAST:event_comboFieldIDMouseReleased

    private void smsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smsKeyTyped
        validations.validateNumber(sms, evt);
    }//GEN-LAST:event_smsKeyTyped

    private void stsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stsKeyTyped
       validations.validateNumber(sts, evt);
    }//GEN-LAST:event_stsKeyTyped

    private void atsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atsKeyTyped
        validations.validateNumber(ats, evt);
    }//GEN-LAST:event_atsKeyTyped

    private void sasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sasKeyTyped
       validations.validateNumber(sas, evt);
    }//GEN-LAST:event_sasKeyTyped

    private void lsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lsKeyTyped
        validations.validateNumber(ls, evt);
    }//GEN-LAST:event_lsKeyTyped

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        Login l=new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logout4MouseClicked

    /**
     *
     */
    public void clear() {
        CropType.setText("");
        sms.setText("");
        sts.setText("");
        ats.setText("");
        sas.setText("");
        ls.setText("");
        comboLocation.setSelectedItem("Select an option");
        comboFarmer.setSelectedItem("Select an option");
        comboFieldID.setSelectedItem("Select an option");

        theSensors.removeAll(theSensors);

        try {
            for (sensorDetails sensorDetails : Serialization.deserializeSensors()) {
                theSensors.addSensorDetails(sensorDetails);
                sensorDetails.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     *
     * @param fieldId
     * @param AirTempreture
     * @return
     */
    public String calculateSaturationVapourPressure(String fieldId, double AirTempreture) {
        String pressureResult = "", status = "";
        double minTemp = 0, maxTemp = 0, saturationVapourPressure = 0, nowPressure = 0;
        for (farms farm : thefarms) {

            if (farm.getfarmNumber() == Integer.parseInt(fieldId)) {
                minTemp = farm.getMinTemp();
                maxTemp = farm.getMaxTemp();
                saturationVapourPressure = farm.getSaturationVapourPressure();
                break;
            }
        }

        if (minTemp > AirTempreture) {
            minTemp = AirTempreture;
        }
        if (maxTemp < AirTempreture) {
            maxTemp = AirTempreture;
        }

        double pressureMax = 0.6108 * (Math.exp((17.27 * (maxTemp)) / (maxTemp + 237.3)));
        double pressureMin = 0.6108 * (Math.exp((17.27 * (minTemp)) / (minTemp + 237.3)));
        nowPressure = (pressureMax + pressureMin) / 2;

        if (saturationVapourPressure > nowPressure) {
            pressureResult = "down";
        } else {
            pressureResult = "up";
        }

        for (farms farm : thefarms) {

            if (farm.getfarmNumber() == Integer.parseInt(fieldId)) {
                try {
                    farm.setMaxTemp(maxTemp);
                    farm.setMinTemp(minTemp);
                    farm.setSaturationVapourPressure(nowPressure);
                    Serialization.Serialize(thefarms, FILE_NAME_farms);
                } catch (Exception ex) {
                    System.out.println("Error updating min max values of fields");
                }
                break;
            }
        }

        return pressureResult;
    }

    /**
     *
     * @param fieldID
     * @param Crop
     * @param SoilMoisture
     * @param SoilTemperature
     * @param AirTemperature
     * @param SoilAcidity
     * @param Lights_Sensor
     * @return
     */
    public String addDetails(String fieldID, String Crop, double SoilMoisture, double SoilTemperature, double AirTemperature, double SoilAcidity, double Lights_Sensor) {
        String status = "";

        sensorDetails s1 = new sensorDetails();
        sensorDetails s2 = new sensorDetails();
        sensorDetails s3 = new sensorDetails();
        sensorDetails s4 = new sensorDetails();
        sensorDetails s5 = new sensorDetails();

        s1.setBehaviour(new Soil_Moisture(Crop));
        s2.setBehaviour(new Soil_Temperature());
        s3.setBehaviour(new Air_Temperature());
        s4.setBehaviour(new Soil_Acidity());
        s5.setBehaviour(new Lights_Sensor());

        String SoilMoistureSol = s1.checkSolution(SoilMoisture);
        String SoilTemperatureSol = s2.checkSolution(SoilTemperature);
        String AirTemperatureSol = s3.checkSolution(AirTemperature);
        String SoilAciditySol = s4.checkSolution(SoilAcidity);
        String Lights_SensorSol = s5.checkSolution(Lights_Sensor);

        String dateTime = Calendar.getInstance().getTime().toString();

        theSensors.addSensorDetails(new sensorDetails(dateTime, fieldID, SoilMoisture, SoilTemperature, AirTemperature, SoilAcidity, Lights_Sensor));
        try {
            Serialization.Serialize(theSensors, FILE_NAME_Sensors);
            JOptionPane.showMessageDialog(this, "Please take the below steps : \n \u2022" + SoilMoistureSol + "\n \u2022" + SoilTemperatureSol + "\n \u2022"
                    + AirTemperatureSol + "\n \u2022" + SoilAciditySol + "\n \u2022" + Lights_SensorSol + "\n Above Solutions may increase plant growth and yield \n \u2022 Mean Saturation Vapour Pressure has gone " + calculateSaturationVapourPressure(fieldID, AirTemperature),
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            status = "success";
        } catch (IOException | HeadlessException ex) {
            status = "fail";
            System.out.println(ex.getMessage());
        }
        return status;
    }

    //load comboboxes
    /**
     *
     * @param combobox
     * @param values
     */
    public void loadCombo(JComboBox combobox, String[] values) {
        combobox.removeAllItems();
        combobox.addItem("Select an option");
        for (int i = 2; i < values.length; i++) {
            combobox.addItem(values[i]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageSensorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageSensorDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CropType;
    private javax.swing.JButton add;
    private javax.swing.JTextField ats;
    private javax.swing.JComboBox comboFarmer;
    private javax.swing.JComboBox comboFieldID;
    private javax.swing.JComboBox comboLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logedUser;
    private javax.swing.JLabel logout4;
    private javax.swing.JTextField ls;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sas;
    private javax.swing.JTextField sms;
    private javax.swing.JTextField sts;
    private javax.swing.JTextField txtancName;
    // End of variables declaration//GEN-END:variables
}
