/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.farm.SetOfFarm;
import Classes.farm.farms;
import Classes.serialization.Serialization;
import Validations.validations;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gihan
 */
public class manage_farm extends javax.swing.JFrame {

    public static SetOfFarm thefarms = new SetOfFarm();
    public static SetOfFarm searchfarm = new SetOfFarm();
    public static final String FILE_NAME_farms = "DataFiles/farms.txt";
    JFileChooser chooser;
    FileNameExtensionFilter filter;
    FileInputStream fis;

    /**
     * Creates new form manage_farm
     */
    String username, userLevel;
    String workingDir = System.getProperty("user.dir");

    /**
     *
     */
    public manage_farm() {
        initComponents();
    }

    /**
     *
     * @param username
     * @param userLevel
     * @param email
     */
    public manage_farm(String username, String userLevel, String email) {
        initComponents();
        this.username = username;
        this.userLevel = userLevel;
        logedUser.setText(email);

        try {
            for (farms farm : Serialization.deserializeFarm()) {
                thefarms.addfarm(farm);
                farm.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        TableLoad(farmtable, thefarms);
        ImageIcon image = new ImageIcon(workingDir + "\\Images\\image.jpg");
        imageIcon.setIcon(image);
        Image img = ((ImageIcon) imageIcon.getIcon()).getImage();
        Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon imi = new ImageIcon(newimg);
        imageIcon.setIcon(imi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_latitude = new javax.swing.JTextField();
        cmb_farmtype = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imageIcon = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtancName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        updatefarm = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        deletefarm = new javax.swing.JButton();
        btnpAddCart5 = new javax.swing.JButton();
        btnpAddCart6 = new javax.swing.JButton();
        txtsearchfarm = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        addfarm = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txt_farmername = new javax.swing.JTextField();
        txt_location = new javax.swing.JTextField();
        txt_longitude = new javax.swing.JTextField();
        txt_fieldid = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        farmtable = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        logedUser = new javax.swing.JLabel();
        logout4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_latitude.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_latitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_latitudeActionPerformed(evt);
            }
        });
        txt_latitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_latitudeKeyTyped(evt);
            }
        });
        getContentPane().add(txt_latitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 160, 30));

        cmb_farmtype.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        cmb_farmtype.setForeground(new java.awt.Color(102, 102, 102));
        cmb_farmtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Harvest", "Maize", "corn", "Barley", "Wheat", "Rice", "Soybean", "Rye", "Coffee" }));
        cmb_farmtype.setBorder(null);
        getContentPane().add(cmb_farmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Farm type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Farmer name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("longitude  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, -1));
        getContentPane().add(imageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 160, 100));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("latitude     :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 90, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Location    :");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 90, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Farmer name   :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 170, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Field ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 120, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 160, 100));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SemMainLogo.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 480, 150));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Product Sales");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Admin Panal");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Data Analysis");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Field Stations");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 150, 30));

        txtancName.setEditable(false);
        txtancName.setBackground(new java.awt.Color(255, 255, 255));
        txtancName.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtancName.setForeground(new java.awt.Color(102, 102, 102));
        txtancName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtancName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtancNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtancName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 620, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Manage Users");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Manage Sensor Details");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 250, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Manage Crop");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 240, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 10, 350));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Manage Products ");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 190, 40));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Add Product");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, 40));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Update Product");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 190, 40));

        updatefarm.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        updatefarm.setForeground(new java.awt.Color(102, 102, 102));
        updatefarm.setText("Update");
        updatefarm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updatefarm.setContentAreaFilled(false);
        updatefarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatefarmMouseClicked(evt);
            }
        });
        getContentPane().add(updatefarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 100, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 153));
        jLabel31.setText("Manage Fields");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 190, 40));

        deletefarm.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        deletefarm.setForeground(new java.awt.Color(102, 102, 102));
        deletefarm.setText("Delete");
        deletefarm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deletefarm.setContentAreaFilled(false);
        deletefarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletefarmMouseClicked(evt);
            }
        });
        getContentPane().add(deletefarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 110, 30));

        btnpAddCart5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        btnpAddCart5.setForeground(new java.awt.Color(102, 102, 102));
        btnpAddCart5.setText("Reset");
        btnpAddCart5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnpAddCart5.setContentAreaFilled(false);
        btnpAddCart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpAddCart5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpAddCart5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 120, 30));

        btnpAddCart6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        btnpAddCart6.setForeground(new java.awt.Color(102, 102, 102));
        btnpAddCart6.setText("Upload");
        btnpAddCart6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnpAddCart6.setContentAreaFilled(false);
        btnpAddCart6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpAddCart6MouseClicked(evt);
            }
        });
        getContentPane().add(btnpAddCart6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 160, 30));

        txtsearchfarm.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        txtsearchfarm.setForeground(new java.awt.Color(102, 102, 102));
        txtsearchfarm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtsearchfarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchfarmMouseClicked(evt);
            }
        });
        txtsearchfarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchfarmActionPerformed(evt);
            }
        });
        txtsearchfarm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchfarmKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearchfarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 290, 40));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 40, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 10));

        jLabel34.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Manage Fertilizer");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 190, 40));

        addfarm.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        addfarm.setForeground(new java.awt.Color(102, 102, 102));
        addfarm.setText("Add");
        addfarm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addfarm.setContentAreaFilled(false);
        addfarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfarmMouseClicked(evt);
            }
        });
        addfarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfarmActionPerformed(evt);
            }
        });
        getContentPane().add(addfarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 130, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min2.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Min.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 20));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max2.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Max.png"))); // NOI18N
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 40, 20));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close2.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 40, 20));

        txt_farmername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_farmername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_farmernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_farmername, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 160, 30));

        txt_location.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_locationActionPerformed(evt);
            }
        });
        getContentPane().add(txt_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 160, 30));

        txt_longitude.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_longitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_longitudeActionPerformed(evt);
            }
        });
        txt_longitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_longitudeKeyTyped(evt);
            }
        });
        getContentPane().add(txt_longitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 160, 30));

        txt_fieldid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_fieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fieldidActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 160, 30));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 230, 10));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        farmtable.setForeground(new java.awt.Color(153, 153, 153));
        farmtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        farmtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        farmtable.setFillsViewportHeight(true);
        farmtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(farmtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 610, 260));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 230, 10));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 230, 10));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 240, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footer.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel32.setText("Agriculture Sensoring Sys");
        jLabel32.setToolTipText("");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 4, 130, 20));

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("www.Agrivi.com/Agriculture Sensoring/adminPanal.htm");
        jLabel35.setToolTipText("");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 31, 540, 20));

        logedUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        logedUser.setForeground(new java.awt.Color(102, 102, 102));
        logedUser.setText("logged User");
        getContentPane().add(logedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 50));

        logout4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        logout4.setForeground(new java.awt.Color(102, 102, 102));
        logout4.setText("Log Out");
        logout4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
        });
        getContentPane().add(logout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 90, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txt_latitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_latitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_latitudeActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        userManagement a = new userManagement(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        manageSensorDetails m = new manageSensorDetails(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        AddCrop a = new AddCrop(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        AddNewProduct a = new AddNewProduct(username, userLevel, logedUser.getText());
        a.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        ProductStock p = new ProductStock(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();

        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        manage_farm m = new manage_farm(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        fertilizerManagement f = new fertilizerManagement(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void btnpAddCart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpAddCart5ActionPerformed
        reset();
    }//GEN-LAST:event_btnpAddCart5ActionPerformed

    private void txtsearchfarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchfarmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchfarmActionPerformed

    private void txt_fieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fieldidActionPerformed

    private void addfarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfarmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addfarmActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_farmernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_farmernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_farmernameActionPerformed

    private void txt_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_locationActionPerformed

    private void txt_longitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_longitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_longitudeActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        viewSensorDetails v = new viewSensorDetails(username, userLevel, logedUser.getText());
        v.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        ProductSale p = new ProductSale(username, userLevel, logedUser.getText());
        p.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        manage_farm m = new manage_farm(username, userLevel, logedUser.getText());
        m.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtancNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtancNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtancNameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        field_harvest f = new field_harvest(username, userLevel, logedUser.getText());
        f.setVisible(true);
        this.hide();
        thefarms.removeAll(thefarms);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addfarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfarmMouseClicked
        
        String farmtype, farmername, fieldid, location, longitude, latitude;
        if (cmb_farmtype.getSelectedItem().toString().equals("Select") || txt_farmername.getText().isEmpty() || txt_location.getText().isEmpty()
                || txt_longitude.getText().isEmpty() || txt_latitude.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide all the details...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            farmtype = cmb_farmtype.getSelectedItem().toString();
            farmername = txt_farmername.getText();
            location = txt_location.getText();
            longitude = txt_longitude.getText();
            latitude = txt_latitude.getText();
            Icon icon = imageIcon.getIcon();

            BufferedImage image = new BufferedImage(icon.getIconWidth(),
                    icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = image.createGraphics();
            icon.paintIcon(null, g2d, 0, 0);
            g2d.dispose();

            try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                ImageOutputStream ios = ImageIO.createImageOutputStream(baos);
                try {
                    ImageIO.write(image, "png", ios);
                    // Set a flag to indicate that the write was successful
                } finally {
                    ios.close();
                }
                byte[] imageInByte = baos.toByteArray();

                String status = addfarm(farmtype, farmername, location, longitude, latitude, imageInByte);
                if (status.equals("success")) {
                    try {
                        Serialization.Serialize(thefarms, FILE_NAME_farms);
                    } catch (IOException ex) {
                        Logger.getLogger(userManagement.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "You have added the farm successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    TableLoad(farmtable, thefarms);

                } else {
                    JOptionPane.showMessageDialog(this, "Registration unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(manage_farm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addfarmMouseClicked

    private void txtsearchfarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchfarmMouseClicked
        // TODO add your handling code here:
        txtsearchfarm.setText("");
    }//GEN-LAST:event_txtsearchfarmMouseClicked

    private void txtsearchfarmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchfarmKeyReleased
        // TODO add your handling code here:
        if (!txtsearchfarm.getText().equalsIgnoreCase("")) {
            searchfarm = thefarms.getfarmFromfarmerName(txtsearchfarm.getText());
            TableLoad(farmtable, searchfarm);

        }
    }//GEN-LAST:event_txtsearchfarmKeyReleased

    private void updatefarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatefarmMouseClicked
        // TODO add your handling code here:
        String farmtype, farmername, location, longitude, latitude;
        if (cmb_farmtype.getSelectedItem().toString().equals("Select") || txt_farmername.getText().isEmpty() || txt_location.getText().isEmpty()
                || txt_longitude.getText().isEmpty() || txt_latitude.getText().isEmpty() || txt_fieldid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide all the details...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            farmtype = cmb_farmtype.getSelectedItem().toString();
            farmername = txt_farmername.getText();
            location = txt_location.getText();
            longitude = txt_longitude.getText();
            latitude = txt_latitude.getText();
            Icon icon = imageIcon.getIcon();

            BufferedImage image = new BufferedImage(icon.getIconWidth(),
                    icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = image.createGraphics();
            icon.paintIcon(null, g2d, 0, 0);
            g2d.dispose();

            try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                ImageOutputStream ios = ImageIO.createImageOutputStream(baos);
                try {
                    ImageIO.write(image, "png", ios);
                    // Set a flag to indicate that the write was successful
                } finally {
                    ios.close();
                }
                byte[] imageInByte = baos.toByteArray();

                farms farm = thefarms.getfarmFromNumber(Integer.parseInt(txt_fieldid.getText())).firstElement();
                String status = thefarms.updatedetails(farm, farmtype, farmername, location, longitude, latitude, imageInByte);
                if (status.equals("success")) {
                    try {
                        Serialization.Serialize(thefarms, FILE_NAME_farms);
                    } catch (IOException ex) {
                        Logger.getLogger(userManagement.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "You have updated successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    TableLoad(farmtable, thefarms);

                } else {
                    JOptionPane.showMessageDialog(this, "Update unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(manage_farm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updatefarmMouseClicked

    private void deletefarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletefarmMouseClicked

        int farmNum;
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this farm?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            if (txt_fieldid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a farm to delete...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                farmNum = Integer.parseInt(txt_fieldid.getText());

                farms farm = thefarms.getfarmFromNumber(Integer.parseInt(txt_fieldid.getText())).firstElement();
                boolean status = thefarms.removefarm(farm);
                if (status) {
                    try {
                        Serialization.Serialize(thefarms, FILE_NAME_farms);
                    } catch (IOException ex) {
                        Logger.getLogger(userManagement.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "You have deleted successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    TableLoad(farmtable, thefarms);

                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_deletefarmMouseClicked

    private void btnpAddCart6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpAddCart6MouseClicked
        get_image();
    }//GEN-LAST:event_btnpAddCart6MouseClicked

    private void farmtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmtableMouseClicked

        // when user click on tbInfo table, all the information what in user selected row will want to show on Update tab
        //  load info to update tab
        DefaultTableModel dtm = (DefaultTableModel) farmtable.getModel();

        int row = farmtable.getSelectedRow();

        txt_fieldid.setText(farmtable.getValueAt(row, 0).toString());
        cmb_farmtype.setSelectedItem(farmtable.getValueAt(row, 1).toString());
        txt_farmername.setText(farmtable.getValueAt(row, 2).toString());
        txt_location.setText(farmtable.getValueAt(row, 3).toString());
        txt_longitude.setText(farmtable.getValueAt(row, 4).toString());
        txt_latitude.setText(farmtable.getValueAt(row, 5).toString());
        for (farms farm : thefarms) {

            if (farm.getfarmNumber() == Integer.parseInt(txt_fieldid.getText())) {
                BufferedImage bufferedImage = null;
                try {
                    InputStream inputStream = new ByteArrayInputStream(farm.getimage());
                    bufferedImage = ImageIO.read(inputStream);
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
                Image img = bufferedImage;
                Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
                ImageIcon imi = new ImageIcon(newimg);
                imageIcon.setIcon(imi);
                System.out.print(farm.getimage());
                break;
            }
        }
    }//GEN-LAST:event_farmtableMouseClicked

    private void txt_longitudeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_longitudeKeyTyped
        validations.validateNumber(txt_longitude, evt);
    }//GEN-LAST:event_txt_longitudeKeyTyped

    private void txt_latitudeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_latitudeKeyTyped
        validations.validateNumber(txt_latitude, evt);
    }//GEN-LAST:event_txt_latitudeKeyTyped

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        Login l=new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logout4MouseClicked

    /**
     *
     */
    public void reset() {
        txt_fieldid.setText("");
        cmb_farmtype.setSelectedIndex(0);
        txt_farmername.setText(" ");
        txt_location.setText(" ");
        txt_longitude.setText(" ");
        txt_latitude.setText(" ");
        ImageIcon image = new ImageIcon(workingDir + "\\Images\\image.jpg");
        imageIcon.setIcon(image);
        Image img = ((ImageIcon) imageIcon.getIcon()).getImage();
        Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon imi = new ImageIcon(newimg);
        imageIcon.setIcon(imi);
        thefarms.removeAll(thefarms);
        try {
            for (farms farm : Serialization.deserializeFarm()) {
                thefarms.addfarm(farm);
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     *
     */
    public void get_image() {
        chooser = new JFileChooser();
        filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getAbsolutePath());
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon imi = new ImageIcon(newimg);
            imageIcon.setIcon(imi);
        }
    }

    /**
     *
     * @param table
     * @param searchList
     */
    public void TableLoad(JTable table, SetOfFarm searchList) {
        String[] colName = {"Farm ID", "Farm Type", "Farmer Name", "Location ", "Longitude", "Latitude"};
        Object[][] object = new Object[searchList.size()][6];
        int i = 0;
        if (searchList.size() != 0) {
            for (farms farm : searchList) {
                object[i][0] = farm.getfarmNumber();
                object[i][1] = farm.getfarmtype();
                object[i][2] = farm.getfarmername();
                object[i][3] = farm.getlocation();
                object[i][4] = farm.getlongitude();
                object[i][5] = farm.getlatitude();
                i++;

            }
        }

        DefaultTableModel model = new DefaultTableModel(object, colName) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        table.setModel(model);
        table.setRowSorter(new TableRowSorter<>(model));
        table.setAutoscrolls(true);
        table.getTableHeader().setReorderingAllowed(false);
    }

    //reister a new farm
    public String addfarm(String farmtype, String farmername, String location, String longitude, String latitude, byte[] image) {
        String status = "";
        new farms.SingletonBuilder(farmtype, farmername, location, longitude, latitude).image(image).build();
        thefarms.addfarm(farms.getInstance());
        try {
            Serialization.Serialize(thefarms, FILE_NAME_farms);
            status = "success";
        } catch (Exception ex) {
            status = "fail";
            System.out.println(ex.getMessage());
        }

        return status;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_farm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_farm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfarm;
    private javax.swing.JButton btnpAddCart5;
    private javax.swing.JButton btnpAddCart6;
    private javax.swing.JComboBox cmb_farmtype;
    private javax.swing.JButton deletefarm;
    private javax.swing.JTable farmtable;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logedUser;
    private javax.swing.JLabel logout4;
    private javax.swing.JTextField txt_farmername;
    private javax.swing.JTextField txt_fieldid;
    private javax.swing.JTextField txt_latitude;
    private javax.swing.JTextField txt_location;
    private javax.swing.JTextField txt_longitude;
    private javax.swing.JTextField txtancName;
    private javax.swing.JTextField txtsearchfarm;
    private javax.swing.JButton updatefarm;
    // End of variables declaration//GEN-END:variables
}
