/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.farm.SetOfFarm;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Sachi
 */
public class adminOptions extends javax.swing.JFrame {

    /**
     * Creates new form field_harvest1
     */
    String userName, userLevel, email;
    public static SetOfFarm thefarms = new SetOfFarm();
    public static SetOfFarm searchfarm = new SetOfFarm();
    public static final String FILE_NAME_farms = "DataFiles/farms.txt";
    String workingDir = System.getProperty("user.dir");

    /**
     *
     */
    public adminOptions() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }

    /**
     *
     * @param userName
     * @param userLevel
     * @param email
     */
    public adminOptions(String userName, String userLevel, String email) {
        initComponents();
        this.userName = userName;
        this.userLevel = userLevel;
        this.email = email;
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cropM = new javax.swing.JButton();
        ProductM = new javax.swing.JButton();
        StockM = new javax.swing.JButton();
        FertilizerM = new javax.swing.JButton();
        SensorM = new javax.swing.JButton();
        userM = new javax.swing.JButton();
        FarmM = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Log Out");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 40));

        cropM.setText("Manage Crop");
        cropM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cropMMouseClicked(evt);
            }
        });
        getContentPane().add(cropM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 230, 30));

        ProductM.setText("Manage Product");
        ProductM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductMMouseClicked(evt);
            }
        });
        getContentPane().add(ProductM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 230, 30));

        StockM.setText("Manage Product Stock");
        StockM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockMMouseClicked(evt);
            }
        });
        getContentPane().add(StockM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 30));

        FertilizerM.setText("Manage Fertilizers");
        FertilizerM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FertilizerMMouseClicked(evt);
            }
        });
        getContentPane().add(FertilizerM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 230, 30));

        SensorM.setText("Manage Sensor Details");
        SensorM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SensorMMouseClicked(evt);
            }
        });
        getContentPane().add(SensorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 230, 30));

        userM.setText("Manage Users");
        userM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMMouseClicked(evt);
            }
        });
        getContentPane().add(userM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 30));

        FarmM.setText("Manage Farms");
        FarmM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FarmMMouseClicked(evt);
            }
        });
        getContentPane().add(FarmM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 230, 30));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Admin Panal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 180, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        Adminandroid a = new Adminandroid(userName, userLevel, email);
        a.setVisible(true);
        this.hide();

    }//GEN-LAST:event_backMouseClicked

    private void userMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMMouseClicked
        userManageOptions u = new userManageOptions(userName, userLevel, email);
        u.setVisible(true);
        this.hide();
    }//GEN-LAST:event_userMMouseClicked

    private void SensorMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SensorMMouseClicked
        manageSensorDetails v = new manageSensorDetails(userName, userLevel, email);
        v.setVisible(true);
        this.hide();
    }//GEN-LAST:event_SensorMMouseClicked

    private void cropMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cropMMouseClicked
      CropList v = new CropList(userName, userLevel, email);
        v.setVisible(true);
        this.hide();
    }//GEN-LAST:event_cropMMouseClicked

    private void ProductMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductMMouseClicked
        ProductList v = new ProductList(userName, userLevel, email);
        v.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ProductMMouseClicked

    private void StockMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMMouseClicked
        ProductStockList f = new ProductStockList(userName, userLevel, email);
        f.setVisible(true);
        this.hide();
    }//GEN-LAST:event_StockMMouseClicked

    private void FertilizerMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FertilizerMMouseClicked
        fertilizerManageOptions f = new fertilizerManageOptions(userName, userLevel, email);
        f.setVisible(true);
        this.hide();
    }//GEN-LAST:event_FertilizerMMouseClicked

    private void FarmMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FarmMMouseClicked
        farmManageOptions f = new farmManageOptions(userName, userLevel, email);
        f.setVisible(true);
        this.hide();
    }//GEN-LAST:event_FarmMMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Moblogin m = new Moblogin();
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FarmM;
    private javax.swing.JButton FertilizerM;
    private javax.swing.JButton ProductM;
    private javax.swing.JButton SensorM;
    private javax.swing.JButton StockM;
    private javax.swing.JLabel back;
    private javax.swing.JButton cropM;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton userM;
    // End of variables declaration//GEN-END:variables
}
