/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.Product.SetOfProducts;
import Classes.farm.SetOfFarm;
import Classes.harvest.HarvestImp;
import Classes.harvest.SetOfHarvest;
import Classes.serialization.Serialization;
import Classes.user.SetOfUsers;
import Classes.user.User;
import static UI.AddCrop.FILE_NAME_Crops;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lakmi
 */
public class CropList extends javax.swing.JFrame {

    /**
     * Creates new form CropList
     */
    public static HarvestImp crop = new HarvestImp();
    public static final String FILE_NAME_Crops = "DataFiles/harvest.txt";
    private SetOfHarvest cropSet = new SetOfHarvest();
    private Serialization serialize = new Serialization();
    public static String cropID = "";
    String username, userLevel, email;

    public CropList() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));

        try {
            for (HarvestImp crop : Serialization.deserializeHarvest()) {
                cropSet.addCrop(crop);

            }
        } catch (IOException ex) {
            Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListLoad(cropSet);
    }

    public CropList(String userName, String userLevel, String email) {
        initComponents();
        this.username = userName;
        this.userLevel = userLevel;
        this.email = email;
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));

        try {
            for (HarvestImp crop : Serialization.deserializeHarvest()) {
                cropSet.addCrop(crop);

            }
        } catch (IOException ex) {
            Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListLoad(cropSet);
    }

    /**
     *
     * load the list of crop
     *
     * @param crops
     */
    public void ListLoad(SetOfHarvest crops) {

        DefaultListModel listModel = new DefaultListModel();

        int i = 0;
        String data = "";
        listModel.addElement("CropID   Crop Name");
        if (crops.size() != 0) {
            for (HarvestImp crop : crops) {
                data = crop.getharvestID() + "            " + crop.getName();
                i++;
                listModel.addElement(data);
            }
        }

        lcCropList.setModel(listModel);
        lcCropList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * clear all
     */
    public void clear() {
        cropSet.removeAll(cropSet);

        try {
            for (HarvestImp crop : Serialization.deserializeHarvest()) {
                cropSet.addCrop(crop);

            }
        } catch (IOException ex) {
            Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtcSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lcCropList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Crops");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/download.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        txtcSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtcSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtcSearch.setText("Search by Crop Name");
        txtcSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtcSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 260, 40));

        lcCropList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lcCropList.setForeground(new java.awt.Color(102, 102, 102));
        lcCropList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lcCropList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lcCropListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lcCropList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void txtcSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcSearchKeyReleased
        SetOfHarvest search = new SetOfHarvest();

        if (!txtcSearch.getText().toString().equalsIgnoreCase("")) {
            search = cropSet.getCropFromName(txtcSearch.getText());
            //loadCrop(search);
            ListLoad(search);
        }
    }//GEN-LAST:event_txtcSearchKeyReleased

    private void lcCropListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lcCropListValueChanged
        String id = lcCropList.getSelectedValue().toString();
        String[] parts = id.split(" ");
        cropID = parts[0];
    }//GEN-LAST:event_lcCropListValueChanged

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this product?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == 0) {
            if (cropID.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a product to delete...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {

                HarvestImp crop = cropSet.getCropFromID(Integer.parseInt(cropID)).firstElement();
                System.out.println("delete product" + crop);

                if (cropSet.removeProduct(crop)) {

                    try {
                        Serialization.Serialize(cropSet, FILE_NAME_Crops);
                    } catch (IOException ex) {
                        Logger.getLogger(CropList.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    ListLoad(cropSet);
                    JOptionPane.showMessageDialog(this, "Delete Sucsessfully", "Message", JOptionPane.PLAIN_MESSAGE);
                    clear();

                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            clear();

        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        if (!cropID.equals("")) {
            CropStock u = new CropStock(username, userLevel, email, cropID);
            u.setVisible(true);
            this.hide();
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a crop to update...", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       CropStock cs= new CropStock(username, userLevel, email);
       cs.show();
       this.hide();
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CropList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lcCropList;
    private javax.swing.JTextField txtcSearch;
    // End of variables declaration//GEN-END:variables
}
