/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.Product.ProductStockImp;
import Classes.Product.SetOfProductStock;
import Classes.Product.SetOfProducts;
import Classes.fertilizer.Fertilizer;
import Classes.fertilizer.SetOfFertilizer;
import Classes.payment.SalesCart;
import Classes.payment.SetOfCart;
import Classes.serialization.Serialization;
import Classes.user.SetOfUsers;
import Classes.user.User;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Kasun
 */
public class fertilizerList extends javax.swing.JFrame {

    public static final String FILE_NAME_Fertilizer = "DataFiles/fertilizer.txt";
    public static SetOfFertilizer theFertilizer = new SetOfFertilizer();
    public static SetOfFertilizer searchFertilizers = new SetOfFertilizer();
    public static String fertilizerID = "";

    /**
     * Creates new form fertilizerList
     */
    String username, userLevel, email;

    public fertilizerList() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }

    public fertilizerList(String userName, String userLevel, String email) {
        initComponents();
        this.username = userName;
        this.userLevel = userLevel;
        this.email = email;

        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
        try {
            for (Fertilizer fertilizer : Serialization.deserializeFertilizer()) {
                theFertilizer.addFertilizer(fertilizer);
                fertilizer.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        ListLoad(listFertilizer, theFertilizer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFertilizer = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnnanpCancel = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        btnanpSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Fertilizer List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/download.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 30, 30));

        search1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        search1.setForeground(new java.awt.Color(153, 153, 153));
        search1.setText("Search by Fertilizer Name ...");
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search1MouseEntered(evt);
            }
        });
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        getContentPane().add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 260, 40));

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/back.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/back1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 40));

        listFertilizer.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        listFertilizer.setForeground(new java.awt.Color(153, 153, 153));
        listFertilizer.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listFertilizer.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFertilizerValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listFertilizer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        btnnanpCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel.png"))); // NOI18N
        btnnanpCancel.setContentAreaFilled(false);
        btnnanpCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel1.png"))); // NOI18N
        btnnanpCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnanpCancelMouseClicked(evt);
            }
        });
        btnnanpCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnanpCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnnanpCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 100, 40));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        btnanpSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/OK.png"))); // NOI18N
        btnanpSave.setContentAreaFilled(false);
        btnanpSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/OK1.png"))); // NOI18N
        btnanpSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnanpSaveMouseClicked(evt);
            }
        });
        btnanpSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanpSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnanpSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnnanpCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnanpCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnnanpCancelMouseClicked

    private void btnnanpCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnanpCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnanpCancelActionPerformed

    private void btnanpSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanpSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnanpSaveMouseClicked

    private void btnanpSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanpSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnanpSaveActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased

        if (!search1.getText().equalsIgnoreCase("")) {
            searchFertilizers = theFertilizer.getFertilizerFromName(search1.getText());
            ListLoad(listFertilizer, searchFertilizers);

        }
    }//GEN-LAST:event_search1KeyReleased

    private void search1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseEntered
        search1.setText("");
    }//GEN-LAST:event_search1MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        fertilizerManageOptions d = new fertilizerManageOptions(username, userLevel, email);
        d.setVisible(true);
        this.hide();
        listFertilizer.removeAll();
        theFertilizer.removeAll(theFertilizer);
        searchFertilizers.removeAll(searchFertilizers);
    }//GEN-LAST:event_jButton1MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int fertilizerNum;
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this fertilizer?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            if (fertilizerID.equals(" ") || fertilizerID.equals("Fertilizer")) {
                JOptionPane.showMessageDialog(this, "Please select a fertilizer to delete...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                fertilizerNum = Integer.parseInt(fertilizerID);

                Fertilizer fertilizer = theFertilizer.getFertilizerFromNumber(Integer.parseInt(fertilizerID)).firstElement();
                boolean status = theFertilizer.removeFertilizer(fertilizer);
                if (status) {
                    try {
                        Serialization.Serialize(theFertilizer, FILE_NAME_Fertilizer);
                    } catch (IOException ex) {
                        Logger.getLogger(userList.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "You have deleted successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                    fertilizerID = "";
                    theFertilizer.removeAll(theFertilizer);
                    try {
                        for (Fertilizer fertilize : Serialization.deserializeFertilizer()) {
                            theFertilizer.addFertilizer(fertilize);
                            fertilizer.print();
                        }
                    } catch (IOException | ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }

                    ListLoad(listFertilizer, theFertilizer);
                    JOptionPane.showMessageDialog(this, "You have deleted successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void listFertilizerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFertilizerValueChanged
        String idx = listFertilizer.getSelectedValue().toString();
        String[] parts = idx.split(" ");
        fertilizerID = parts[0];
    }//GEN-LAST:event_listFertilizerValueChanged

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        if (!fertilizerID.equals("Fertilizer") || !fertilizerID.equals("")) {
            updateFertilizer u = new updateFertilizer(username, userLevel, email);
            u.setVisible(true);
            this.hide();
            listFertilizer.removeAll();
            theFertilizer.removeAll(theFertilizer);
            searchFertilizers.removeAll(searchFertilizers);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Fertilizer to update...", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_updateMouseClicked

    /**
     *
     * @param list
     * @param searchList
     */
    public static void ListLoad(JList list, SetOfFertilizer searchList) {
        DefaultListModel listModel = new DefaultListModel();
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        int i = 0;
        String data = "";
        if (searchList.size() != 0) {
            listModel.addElement("Fertilizer Number Fertilizer Name");
            for (Fertilizer fertilizer : searchList) {
                data = fertilizer.getFertilizerNumber() + "     " + fertilizer.getName();
                i++;

                listModel.addElement(data);
            }

        }

        list.setModel(listModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fertilizerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fertilizerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanpSave;
    private javax.swing.JButton btnnanpCancel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listFertilizer;
    private javax.swing.JTextField search1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
