/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.Product.ProductsImp;
import Classes.Product.SetOfProducts;
import Classes.payment.SalesCart;
import Classes.payment.SetOfCart;
import Classes.serialization.Serialization;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lakmi
 */
public class MyCart extends javax.swing.JFrame {

    /**
     * Creates new form MyCart
     */
    public static SalesCart cart = new SalesCart();
    public static final String FILE_NAME_Cart = "DataFiles/Cart.txt";
    public static final String FILE_NAME_Product = "DataFiles/Products.txt";
    private SetOfCart cartSet = new SetOfCart();
    private SetOfProducts productSet = new SetOfProducts();
    public static String productID = "";
    double qty;
    String username, userLevel, email;

    public MyCart() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }

    public MyCart(String username, String userLevel, String email) {
        initComponents();

        this.username = username;
        this.userLevel = userLevel;
        this.email = email;

        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));

        try {
            for (SalesCart cart : Serialization.deserializeCart()) {
                if (cart.getEmail().equals(username)) {
                    cartSet.addCart(cart);
                    System.out.println(cart.getCartID());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            for (ProductsImp productImp : Serialization.deserializeProducts()) {

                productSet.add(productImp);

            }
        } catch (IOException ex) {
            Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListLoad(cartSet);
    }

    public void clear() {
        productIDtxt.setText("");
        cartSet.removeAll(cartSet);

        try {
            for (SalesCart cart : Serialization.deserializeCart()) {
                if (cart.getEmail().equals(username)) {
                    cartSet.addCart(cart);
                    System.out.println(cart.getCartID());
                }
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     * load the list of product in the users cart
     *
     * @param crops
     */
    public void ListLoad(SetOfCart carts) {

        DefaultListModel listModel = new DefaultListModel();

        int i = 0;
        String data = "";
        listModel.addElement("Product ID    Price   Quantity    Name");
        if (carts.size() != 0) {
            for (SalesCart cart : carts) {
                data = cart.getProductID() + "                 " + cart.getPrice() + "          " + cart.getQuantity() + "        " + cart.getName();
                i++;
                listModel.addElement(data);
            }
        }

        lstmcProductList.setModel(listModel);
        lstmcProductList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remove = new javax.swing.JLabel();
        btnanpSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        productIDtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstmcProductList = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        remove.setText("jLabel10");
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 60, 40));

        btnanpSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/OK.png"))); // NOI18N
        btnanpSave.setContentAreaFilled(false);
        btnanpSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/OK1.png"))); // NOI18N
        btnanpSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnanpSaveMouseClicked(evt);
            }
        });
        btnanpSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanpSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnanpSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("My Cart");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        productIDtxt.setEditable(false);
        productIDtxt.setBackground(new java.awt.Color(255, 255, 255));
        productIDtxt.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        productIDtxt.setForeground(new java.awt.Color(102, 102, 102));
        productIDtxt.setToolTipText("Product ID");
        productIDtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(productIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 180, 30));

        lstmcProductList.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lstmcProductList.setForeground(new java.awt.Color(102, 102, 102));
        lstmcProductList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstmcProductList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstmcProductListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstmcProductList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 144, 260, 260));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 20, 20));

        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnanpSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanpSaveMouseClicked
        Checkout ch = new Checkout(username, userLevel, email);
        ch.show();
        this.hide();
    }//GEN-LAST:event_btnanpSaveMouseClicked

    private void btnanpSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanpSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnanpSaveActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        int productID;

        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this product?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == 0) {
            if (productIDtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a product to remove from cart...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                productID = Integer.parseInt(productIDtxt.getText());

                for (SalesCart cart : cartSet) {
                    if (cart.getProductID() == productID) {

                        if (cartSet.removeCart(cart)) {

                            try {
                                Serialization.Serialize(cartSet, FILE_NAME_Cart);
                                JOptionPane.showMessageDialog(this, "Product removed from the cart Sucsessfully", "Message", JOptionPane.PLAIN_MESSAGE);
                                ProductsImp product = productSet.getProductFromID(productID).elementAt(0);
                                cartSet.updateProductqty(product, qty);

                                clear();
                              
                                ListLoad(cartSet);
                            } catch (IOException ex) {
                                Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {
                            JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                        break;
                    }
                }
            }
        } else {
            clear();
            ListLoad(cartSet);
        }
    }//GEN-LAST:event_removeMouseClicked

    private void lstmcProductListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstmcProductListValueChanged
        String id = lstmcProductList.getSelectedValue().toString();
        String[] parts = id.split(" ");
        productID = parts[0];
        productIDtxt.setText(productID);
    }//GEN-LAST:event_lstmcProductListValueChanged

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        ProductSale cl = new ProductSale(username, userLevel, email);
        cl.show();
        this.hide();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanpSave;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JList lstmcProductList;
    private javax.swing.JTextField productIDtxt;
    private javax.swing.JLabel remove;
    // End of variables declaration//GEN-END:variables
}
