/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.farm.SetOfFarm;
import Classes.farm.farms;
import java.awt.geom.RoundRectangle2D;
import Classes.serialization.Serialization;
import UI.manage_farm;
import UI.userManagement;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gihan
 */
public class newFarm extends javax.swing.JFrame {

    public static SetOfFarm thefarms = new SetOfFarm();
    public static SetOfFarm searchfarm = new SetOfFarm();
    public static final String FILE_NAME_farms = "DataFiles/farms.txt";
    JFileChooser chooser;
    FileNameExtensionFilter filter;
    FileInputStream fis;

    /**
     * Creates new form manage_farm
     */
    String username, userLevel,email;
    String workingDir = System.getProperty("user.dir");

    public newFarm() {
        initComponents();

        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }

    public newFarm(String userName, String userLevel, String email) {
        initComponents();
          this.username = userName;
        this.userLevel = userLevel;
        this.email=email;
        try {
            for (farms farm : Serialization.deserializeFarm()) {
                thefarms.addfarm(farm);
                farm.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        ImageIcon image = new ImageIcon(workingDir + "\\Images\\image.jpg");
        imageIcon.setIcon(image);
        Image img = ((ImageIcon) imageIcon.getIcon()).getImage();
        Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon imi = new ImageIcon(newimg);
        imageIcon.setIcon(imi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addfarm = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_farmtype = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_farmername = new javax.swing.JTextField();
        imageIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnupload = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_location = new javax.swing.JTextField();
        txt_longitude = new javax.swing.JTextField();
        txt_latitude = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addfarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/OK.png"))); // NOI18N
        addfarm.setContentAreaFilled(false);
        addfarm.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/OK1.png"))); // NOI18N
        addfarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfarmMouseClicked(evt);
            }
        });
        getContentPane().add(addfarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 100, 40));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel.png"))); // NOI18N
        reset.setContentAreaFilled(false);
        reset.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel1.png"))); // NOI18N
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 100, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Add New Farm");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, -1));

        cmb_farmtype.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cmb_farmtype.setForeground(new java.awt.Color(102, 102, 102));
        cmb_farmtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paddy field", "grain fields" }));
        cmb_farmtype.setBorder(null);
        getContentPane().add(cmb_farmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Farm type         :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Farmer Name   :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, -1));

        txt_farmername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_farmername.setForeground(new java.awt.Color(102, 102, 102));
        txt_farmername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_farmername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_farmernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_farmername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, -1));

        imageIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(imageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Farm Image      :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, -1));

        btnupload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Upload1.png"))); // NOI18N
        btnupload.setContentAreaFilled(false);
        btnupload.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Upload.png"))); // NOI18N
        btnupload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnuploadMouseClicked(evt);
            }
        });
        getContentPane().add(btnupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 70, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Location           :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, 20));

        txt_location.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_location.setForeground(new java.awt.Color(102, 102, 102));
        txt_location.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, -1));

        txt_longitude.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_longitude.setForeground(new java.awt.Color(102, 102, 102));
        txt_longitude.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_longitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 130, -1));

        txt_latitude.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_latitude.setForeground(new java.awt.Color(102, 102, 102));
        txt_latitude.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_latitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 130, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("latitude            :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("longitude         :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, 20));

        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        reset();
    }//GEN-LAST:event_resetMouseClicked

    private void addfarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfarmMouseClicked
        String farmtype, farmername, fieldid, location, longitude, latitude;
        if (cmb_farmtype.getSelectedItem().toString().equals("Select") || txt_farmername.getText().isEmpty() || txt_location.getText().isEmpty()
                || txt_longitude.getText().isEmpty() || txt_latitude.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide all the details...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            farmtype = cmb_farmtype.getSelectedItem().toString();
            farmername = txt_farmername.getText();
            location = txt_location.getText();
            longitude = txt_longitude.getText();
            latitude = txt_latitude.getText();
            Icon icon = imageIcon.getIcon();

            BufferedImage image = new BufferedImage(icon.getIconWidth(),
                    icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = image.createGraphics();
            icon.paintIcon(null, g2d, 0, 0);
            g2d.dispose();

            try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                ImageOutputStream ios = ImageIO.createImageOutputStream(baos);
                try {
                    ImageIO.write(image, "png", ios);
                    // Set a flag to indicate that the write was successful
                } finally {
                    ios.close();
                }
                byte[] imageInByte = baos.toByteArray();

                String status = addfarm(farmtype, farmername, location, longitude, latitude, imageInByte);
                if (status.equals("success")) {
                    try {
                        Serialization.Serialize(thefarms, FILE_NAME_farms);
                    } catch (IOException ex) {
                        Logger.getLogger(userManagement.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "You have added the farm successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Registration unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(manage_farm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addfarmMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        farmManageOptions u = new farmManageOptions(username, userLevel, email);
        u.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void txt_farmernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_farmernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_farmernameActionPerformed

    private void btnuploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuploadMouseClicked
        get_image();
    }//GEN-LAST:event_btnuploadMouseClicked

    /**
     *
     */
    public void reset() {
        cmb_farmtype.setSelectedIndex(0);
        txt_farmername.setText(" ");
        txt_location.setText(" ");
        txt_longitude.setText(" ");
        txt_latitude.setText(" ");
        ImageIcon image = new ImageIcon(workingDir + "\\Images\\image.jpg");
        imageIcon.setIcon(image);
        Image img = ((ImageIcon) imageIcon.getIcon()).getImage();
        Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon imi = new ImageIcon(newimg);
        imageIcon.setIcon(imi);
        thefarms.removeAll(thefarms);
        try {
            for (farms farm : Serialization.deserializeFarm()) {
                thefarms.addfarm(farm);
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    /**
     *
     */
    public void get_image() {
        chooser = new JFileChooser();
        filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getAbsolutePath());
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon imi = new ImageIcon(newimg);
            imageIcon.setIcon(imi);
        }
    }
    
    //reister a new farm
    public String addfarm(String farmtype, String farmername, String location, String longitude, String latitude, byte[] image) {
        String status = "";
        new farms.SingletonBuilder(farmtype, farmername, location, longitude, latitude).image(image).build();
        thefarms.addfarm(farms.getInstance());
        try {
            Serialization.Serialize(thefarms, FILE_NAME_farms);
            status = "success";
        } catch (Exception ex) {
            status = "fail";
            System.out.println(ex.getMessage());
        }

        return status;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newFarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfarm;
    private javax.swing.JButton btnupload;
    private javax.swing.JComboBox cmb_farmtype;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton reset;
    private javax.swing.JTextField txt_farmername;
    private javax.swing.JTextField txt_latitude;
    private javax.swing.JTextField txt_location;
    private javax.swing.JTextField txt_longitude;
    // End of variables declaration//GEN-END:variables
}
