package UI.MobileUI;

import Classes.Product.ProductStockImp;
import Classes.Product.ProductsImp;
import Classes.Product.SetOfProductStock;
import Classes.Product.SetOfProducts;
import Classes.Product.productObserver;
import Classes.Product.productObserverImp;
import Classes.serialization.Serialization;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lakmi
 */
public class ProductStockList extends javax.swing.JFrame {

    /**
     * Creates new form ProductStockList
     */
    public static ProductStockImp products = new ProductStockImp();
    public static final String FILE_NAME_ProductsStock = "DataFiles/ProductsStock.txt";
    public static final String FILE_NAME_Products = "DataFiles/Products.txt";
    private Serialization serialize = new Serialization();
    private SetOfProductStock productStockSet = new SetOfProductStock();
    private SetOfProducts productSet = new SetOfProducts();
    public static String StockID;
    public static String ProductID;

    String username, userLevel, email;

    public ProductStockList() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }

    /**
     *
     * @param userName
     * @param userLevel
     * @param email
     */
    public ProductStockList(String userName, String userLevel, String email) {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
        this.username = username;
        this.userLevel = userLevel;
        this.email = email;

        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));

        try {
            for (ProductStockImp products : Serialization.deserializeProductsStock()) {
                productStockSet.addProductStock(products);
                System.out.println(products.getProductID());

            }
        } catch (IOException ex) {
            Logger.getLogger(ProductStockList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductStockList.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            for (ProductsImp productImp : Serialization.deserializeProducts()) {
                productSet.addProducts(productImp);
                System.out.println(productImp.getName());

            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(ProductStockList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     *
     * load the list of crop
     *
     * @param products
     */
    public void ListLoad(SetOfProductStock products) {

        DefaultListModel listModel = new DefaultListModel();

        int i = 0;
        String data = "";
        listModel.addElement("StockID       ProductID       Date");
        if (products.size() != 0) {
            for (ProductStockImp product : products) {
                data = product.getStockNo() + "            " + product.getProductID() + "            " + product.getDate();
                i++;
                listModel.addElement(data);
            }
        }

        lcCropList.setModel(listModel);
        lcCropList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * clear all
     */
    public void clear() {

        productStockSet.removeAll(productStockSet);

        try {
            for (ProductStockImp productsStock : Serialization.deserializeProductsStock()) {
                productStockSet.addProductStock(productsStock);

            }

            for (ProductsImp productsMake : Serialization.deserializeProducts()) {
                productSet.addProducts(productsMake);

            }

        } catch (IOException ex) {
            Logger.getLogger(ProductStockList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductStockList.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtcSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lcCropList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/download.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        txtcSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtcSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtcSearch.setText("Search by Date");
        txtcSearch.setToolTipText("");
        txtcSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtcSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 260, 40));

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        btnView.setText("View details");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });
        getContentPane().add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        lcCropList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lcCropList.setForeground(new java.awt.Color(102, 102, 102));
        lcCropList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lcCropList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lcCropListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lcCropList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this product?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.NO_OPTION) {
        } else {

            if (StockID.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a stock record to delete...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {

                ProductStockImp productStk = productStockSet.getProductStockFromStockID(Integer.parseInt(StockID)).firstElement();

                if (productStockSet.removeProductStock(productStk)) {
                    try {
                        Serialization.Serialize(productStockSet, FILE_NAME_ProductsStock);

                    } catch (IOException ex) {
                        Logger.getLogger(ProductStock.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    loadProductStock(productStockSet);
                    JOptionPane.showMessageDialog(this, "Delete Sucsessfully", "Message", JOptionPane.PLAIN_MESSAGE);
                    productObserver observer2 = new productObserverImp(Integer.parseInt(ProductID));
                    productStk.registerObserver(observer2);

                    productStk.setStatus("Remove");
                    clear();
                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtcSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcSearchKeyReleased
        SetOfProductStock search = new SetOfProductStock();

        if (!txtcSearch.getText().equalsIgnoreCase("")) {
            //search = productStockSet.getProductStockFromDate(txtcSearch.getText());
            loadProductStock(productStockSet);

        }
    }//GEN-LAST:event_txtcSearchKeyReleased

    private void lcCropListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lcCropListValueChanged
        String id = lcCropList.getSelectedValue().toString();
        String[] parts = id.split(" ");
        StockID = parts[0];
        ProductID = parts[1];
    }//GEN-LAST:event_lcCropListValueChanged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        productAnalysis pa = new productAnalysis(username, userLevel, email);
        pa.show();
        this.hide();
    }//GEN-LAST:event_btnViewMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        ProductStock ps= new ProductStock(username, userLevel, email);
        ps.show();
        this.hide();
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductStockList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductStockList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductStockList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductStockList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductStockList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lcCropList;
    private javax.swing.JTextField txtcSearch;
    // End of variables declaration//GEN-END:variables

    private void loadProductStock(SetOfProductStock productStockSet) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
