/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.MobileUI;

import Classes.Product.ProductStockImp;
import Classes.Product.ProductsImp;
import Classes.Product.SetOfProducts;
import Classes.serialization.Serialization;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lakmi
 */
public class ProductList extends javax.swing.JFrame {

    /**
     * Creates new form ProductList
     */
    
    public static ProductsImp products = new ProductsImp();
    public static final String FILE_NAME_Products = "DataFiles/Products.txt";
    private SetOfProducts productSet = new SetOfProducts();
    private Serialization serialize = new Serialization();
    public static String ProductID = "";
    String username,userLevel,email;
    
    public ProductList() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }
    
     public ProductList(String username, String userLevel, String email) {
        initComponents();
        
        this.username = username;
        this.userLevel = userLevel;
        this.email = email;
        
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
        
        try {
            for (ProductsImp products : Serialization.deserializeProducts()) {
                productSet.addProducts(products);
                products.print();

            }
        } catch (IOException ex) {
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListLoad(productSet);
    }
     
     /**
     *
     * load the list of products
     *
     * @param crops
     */
    public void ListLoad(SetOfProducts products) {

        DefaultListModel listModel = new DefaultListModel();

        int i = 0;
        String data = "";
        listModel.addElement("ProductID    Name       Unit Price     Total Quantity");
        if (products.size() != 0) {
            for (ProductsImp product : products) {
                data = product.getProductNo()+ "            " + product.getName()+"             "+product.getPrice()+"      "+product.getQuantity();
                i++;
                listModel.addElement(data);
            }
        }

        lcCropList.setModel(listModel);
        lcCropList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * clear all
     */
    public void clear() {
         productSet.removeAll(productSet);
       
        try {
            for (ProductsImp products : Serialization.deserializeProducts()) {
                productSet.addProducts(products);
                products.print();

            }
        } catch (IOException ex) {
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtcSearch = new javax.swing.JTextField();
        btnUpdate1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lcCropList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/download.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        txtcSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtcSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtcSearch.setText("Search by Name");
        txtcSearch.setToolTipText("");
        txtcSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtcSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 260, 40));

        btnUpdate1.setText("Add");
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        lcCropList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lcCropList.setForeground(new java.awt.Color(102, 102, 102));
        lcCropList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lcCropList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lcCropListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lcCropList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
      
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this product?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == 0) {
            if (ProductID.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a product to delete...", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                

                ProductsImp product = productSet.getProductFromID(Integer.parseInt(ProductID)).firstElement();
                System.out.println("delete product" + product);

                if (productSet.removeProduct(product)) {
                    try {
                        Serialization.Serialize(productSet, FILE_NAME_Products);
                    } catch (IOException ex) {
                        Logger.getLogger(AddNewProduct.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ListLoad(productSet) ;
                    JOptionPane.showMessageDialog(this, "Delete Sucsessfully", "Message", JOptionPane.PLAIN_MESSAGE);
                    clear();

                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            clear();

        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtcSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcSearchKeyReleased
        SetOfProducts search = new SetOfProducts();

        if (!txtcSearch.getText().toString().equalsIgnoreCase("")) {
            search = productSet.getProductFromName(txtcSearch.getText());
            ListLoad(productSet);

        }
    }//GEN-LAST:event_txtcSearchKeyReleased

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        AddNewProduct pa = new AddNewProduct(username, userLevel, email,ProductID);
        pa.show();
        this.hide();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void lcCropListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lcCropListValueChanged
        String id = lcCropList.getSelectedValue().toString();
        String[] parts = id.split(" ");
        ProductID = parts[0];
    }//GEN-LAST:event_lcCropListValueChanged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseClicked
        AddNewProduct an=new AddNewProduct(username, userLevel, email);
        an.show();
        this.hide();
    }//GEN-LAST:event_btnUpdate1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lcCropList;
    private javax.swing.JTextField txtcSearch;
    // End of variables declaration//GEN-END:variables
}
