/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.serialization.Serialization;
import Classes.user.SendEmail;
import Classes.user.SetOfRandomCode;
import Classes.user.SetOfUsers;
import Classes.user.User;
import Classes.user.randomCode;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasu
 */
public class resetpassword extends javax.swing.JFrame {

    /**
     * Creates new form resetpassword
     */
    public static SetOfUsers searchUsers = new SetOfUsers();
    public static final String FILE_NAME_Users = "DataFiles/Users.txt";

    public static SetOfRandomCode searchCode = new SetOfRandomCode();
    public static final String FILE_NAME_RandomCodes = "DataFiles/RandomCodes.txt";
    
    public resetpassword() {
        initComponents();
        
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),95,95));
        
        try {
            for (User member : Serialization.deserializeUsers()) {
                searchUsers.addUser(member);
                member.print();
            }

            for (randomCode code : Serialization.deserializeRandomCode()) {
                searchCode.addCode(code);
                code.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    /**
     *
     * @return
     */
    public static String getAlphaNumbericRandom() {
        String chars = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

        int numberOfCodes = 0;
        String code = "";
        while (numberOfCodes < 7) {
            char c = chars.charAt((int) (Math.random() * chars.length()));
            code += c;
            numberOfCodes++;
        }
        return code;
    }

    /**
     *
     * @param email
     * @return
     */
    public static String sendMessage(String email) {
        String verifyCode = getAlphaNumbericRandom();
        String status = "";
        try {
            SendEmail mailSender;
            mailSender = new SendEmail(email, "Verification Message", "Your Verification Code is : " + verifyCode);

            new randomCode.SingletonBuilder(email, verifyCode).build();
            searchCode.addCode(randomCode.getInstance());
            try {
                Serialization.Serialize(searchCode, FILE_NAME_RandomCodes);
                status = "success";
            } catch (Exception ex) {
                status = "fail";
                System.out.println(ex.getMessage());
            }

        } catch (Exception ex) {
            status = "error";
        }
        return status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsenderEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Send.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Send1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 110, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel1.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText(" recover password ");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 130, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Enter your email to send ");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 190, 20));

        txtsenderEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtsenderEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtsenderEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsenderEmail.setBorder(null);
        txtsenderEmail.setPreferredSize(new java.awt.Dimension(3, 29));
        txtsenderEmail.setRequestFocusEnabled(false);
        getContentPane().add(txtsenderEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 155, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Resetback.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Moblogin().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Moblogin().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         if (txtsenderEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide the email address...", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            String status = "";

            for (User user : searchUsers) {
                if (user.getUsername().equals(txtsenderEmail.getText())) {
                    status = "true";
                    break;
                } else {
                    status = "false";
                }
            }

            if (status.equals("true")) {
                String stat = sendMessage(txtsenderEmail.getText());
                if (stat.equals("success")) {
                    try {
                        JOptionPane.showMessageDialog(this, "Varification Code has been send to your email...\n"
                                + " Please type the code below to reset your password ", "Next Step", JOptionPane.INFORMATION_MESSAGE);
                        searchCode.removeAll(searchCode);
                        for (randomCode code : Serialization.deserializeRandomCode()) {
                            searchCode.addCode(code);
                            code.print();
                        }
                        
                        verifyCode v=new verifyCode(txtsenderEmail.getText());
                         
            v.setVisible(true);
            searchCode.removeAll(searchCode);
            txtsenderEmail.setText("");
            this.hide();
                     
                    } catch (IOException | ClassNotFoundException ex) {
                        Logger.getLogger(resetpassword.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Seems to be a internet connection error.. try again later... ", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please Register to the system...", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtsenderEmail;
    // End of variables declaration//GEN-END:variables
}
