/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.serialization.Serialization;
import Classes.user.SetOfUsers;
import Classes.user.User;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun
 */
public class setNewPassword extends javax.swing.JFrame {

    /**
     * Creates new form setNewPassword
     */
    String username,userLevel,email;
    SetOfUsers searchUsers = new SetOfUsers();
    public static final String FILE_NAME_Users = "DataFiles/Users.txt";
    
    public setNewPassword() {
        initComponents();
        
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),95,95));
        
        try {
            for (User user : Serialization.deserializeUsers()) {
                searchUsers.addUser(user);
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }
    
     public setNewPassword(String email) {
        initComponents();
        
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),95,95));
        
        this.email = email;

        try {
            for (User member : Serialization.deserializeUsers()) {
                searchUsers.addUser(member);
                member.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPWD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirmPWD = new javax.swing.JPasswordField();
        resetPwd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPWD.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        newPWD.setForeground(new java.awt.Color(102, 102, 102));
        newPWD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newPWD.setBorder(null);
        newPWD.setPreferredSize(new java.awt.Dimension(3, 29));
        newPWD.setRequestFocusEnabled(false);
        getContentPane().add(newPWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 324, 160, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Reset Password");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 170, 40));

        confirmPWD.setForeground(new java.awt.Color(153, 153, 153));
        confirmPWD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPWD.setBorder(null);
        getContentPane().add(confirmPWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 150, 25));

        resetPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/log1.png"))); // NOI18N
        resetPwd.setContentAreaFilled(false);
        resetPwd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/log2.png"))); // NOI18N
        resetPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPwdMouseClicked(evt);
            }
        });
        getContentPane().add(resetPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel1.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, -1));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Officiallogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        clear();
    }//GEN-LAST:event_jButton2MouseClicked

    public void clear() {
        newPWD.setText("");
        confirmPWD.setText("");
    }
    
    private void resetPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPwdMouseClicked
          if (newPWD.getText().equals(confirmPWD.getText())) {
            String status = updatePassword(email, newPWD.getText());
            if (status.equals("success")) {
                new Moblogin().setVisible(true);
                this.hide();
            } else {
                JOptionPane.showMessageDialog(this, "Error updating the password...Try again later...", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "New Password and Confirm Password must be same...", "Error", JOptionPane.ERROR_MESSAGE);
            newPWD.setText("");
            confirmPWD.setText("");
        }
    }//GEN-LAST:event_resetPwdMouseClicked

     /**
     *
     * @param email
     * @param password
     * @return
     */
    public String updatePassword(String email, String password) {
        String status = "";
        for (User member : searchUsers) {
            if (member.getUsername().equals(email)) {
                member.setPassword(password);
                try {
                    Serialization.Serialize(searchUsers, FILE_NAME_Users);
                    status = "success";
                } catch (IOException ex) {
                    Logger.getLogger(setNewPassword.class.getName()).log(Level.SEVERE, null, ex);
                    status = "error";
                }
                break;
            }
        }

        return status;
    }

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Mainpage().setVisible(true);
         this.hide();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setNewPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPWD;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField newPWD;
    private javax.swing.JButton resetPwd;
    // End of variables declaration//GEN-END:variables
}
