/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MobileUI;

import Classes.fertilizer.Fertilizer;
import Classes.fertilizer.SetOfFertilizer;
import java.awt.geom.RoundRectangle2D;
import Classes.serialization.Serialization;
import Classes.user.SetOfUsers;
import Classes.user.User;
import Validations.validations;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun
 */
public class updateFertilizer extends javax.swing.JFrame {

    /**
     * Creates new form updateFertilizer
     */
    String userName, userLevel, email;
    public static final String FILE_NAME_Fertilizer = "DataFiles/fertilizer.txt";
    public static SetOfFertilizer theFertilizer = new SetOfFertilizer();
    public static SetOfFertilizer searchFertilizers = new SetOfFertilizer();

    public updateFertilizer() {
        initComponents();

        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));
    }

    public updateFertilizer(String userName, String userLevel, String email) {
        initComponents();
        this.userName = userName;
        this.userLevel = userLevel;
        this.email = email;
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 95, 95));

        try {
            for (Fertilizer fertilizer : Serialization.deserializeFertilizer()) {
                theFertilizer.addFertilizer(fertilizer);
                fertilizer.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        for (Fertilizer fertilizer : theFertilizer) {
            if (fertilizer.getFertilizerNumber() == Integer.parseInt(fertilizerList.fertilizerID)) {
                String userL;
                comboSensorType.setSelectedItem(fertilizer.getSensorType());
                Name.setText(fertilizer.getName());
                crops.setText(fertilizer.getCrops());
                min.setText(fertilizer.getMinValue() + "");
                max.setText(fertilizer.getMaxValue() + "");
                qty.setText(fertilizer.getQuntity() + "");
                desc.setText(fertilizer.getDescription());

                break;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboSensorType = new javax.swing.JComboBox();
        Name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        crops = new javax.swing.JTextArea();
        qty = new javax.swing.JTextField();
        min = new javax.swing.JTextField();
        max = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Upload1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/Upload.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 100, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/cancel1.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 20, 20));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Update Fertilizer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, -1));

        comboSensorType.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboSensorType.setForeground(new java.awt.Color(102, 102, 102));
        comboSensorType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sensor Type", "Soil Moisture Sensor", "Soil Acidity Sensor" }));
        comboSensorType.setBorder(null);
        getContentPane().add(comboSensorType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, -1));

        Name.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(102, 102, 102));
        Name.setText("Name");
        Name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameMouseClicked(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        crops.setColumns(15);
        crops.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        crops.setForeground(new java.awt.Color(102, 102, 102));
        crops.setRows(3);
        crops.setText("Crops : Separate each with \",\"");
        crops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cropsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(crops);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 50));

        qty.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        qty.setForeground(new java.awt.Color(102, 102, 102));
        qty.setText("Quantity : Quantity in bottels");
        qty.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        qty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyMouseClicked(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 240, 30));

        min.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        min.setForeground(new java.awt.Color(102, 102, 102));
        min.setText("Minimum Temprature");
        min.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minKeyTyped(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 240, -1));

        max.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        max.setForeground(new java.awt.Color(102, 102, 102));
        max.setText("Maximum Temprature");
        max.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
        });
        max.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxKeyTyped(evt);
            }
        });
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, 30));

        desc.setColumns(15);
        desc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(102, 102, 102));
        desc.setRows(3);
        desc.setText("Discription");
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(desc);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/MobileImages/androback.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        clear();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       String name, SensorType, crop, description;
        double minValue, maxValue;
        int quantity;

        if (Name.getText().isEmpty() || crops.getText().isEmpty() || min.getText().isEmpty()
                || max.getText().isEmpty() || qty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide all the necessary details...", "Error", JOptionPane.ERROR_MESSAGE);

        }else {
             name = Name.getText();
            SensorType = comboSensorType.getSelectedItem().toString();
            crop = crops.getText();
            minValue = Double.parseDouble(min.getText());
            maxValue = Double.parseDouble(max.getText());
            quantity = Integer.parseInt(qty.getText());
            description = desc.getText();

            Fertilizer fertilizer = theFertilizer.getFertilizerFromNumber(Integer.parseInt(fertilizerList.fertilizerID)).firstElement();
            String status = theFertilizer.updatedetails(fertilizer, name, SensorType, crop, description, minValue, maxValue, quantity);
            if (status.equals("success")) {
                 try {
                     Serialization.Serialize(theFertilizer, FILE_NAME_Fertilizer);
                     JOptionPane.showMessageDialog(this, "You have updated successful", "Congradulations", JOptionPane.INFORMATION_MESSAGE);
                     clear();
                     theFertilizer.removeAll(theFertilizer);
                     fertilizerList v = new fertilizerList(userName, userLevel, email);
                     v.setVisible(true);
                     this.hide();
                 } catch (IOException ex) {
                     Logger.getLogger(updateFertilizer.class.getName()).log(Level.SEVERE, null, ex);
                 }

            } else {
                JOptionPane.showMessageDialog(this, "Update unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
            }
       
        }

    }//GEN-LAST:event_jButton3MouseClicked

    /**
     *
     */
    public void clear() {
        comboSensorType.setSelectedItem("Sensor Type");
        Name.setText("");
        crops.setText("");
        qty.setText("");
        min.setText("");
        max.setText("");
        desc.setText("");

        theFertilizer.removeAll(theFertilizer);
        try {
            for (Fertilizer fertilizer : Serialization.deserializeFertilizer()) {
                theFertilizer.addFertilizer(fertilizer);
                fertilizer.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        fertilizerList u = new fertilizerList(userName, userLevel, email);
        u.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMouseClicked
        Name.setText("");
    }//GEN-LAST:event_NameMouseClicked

    private void cropsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cropsMouseClicked
        crops.setText("");
    }//GEN-LAST:event_cropsMouseClicked

    private void qtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyMouseClicked
        qty.setText("");
    }//GEN-LAST:event_qtyMouseClicked

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        validations.validateNumber(qty, evt);
    }//GEN-LAST:event_qtyKeyTyped

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        min.setText("");
    }//GEN-LAST:event_minMouseClicked

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minActionPerformed

    private void minKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minKeyTyped
        validations.validateNumber(min, evt);
    }//GEN-LAST:event_minKeyTyped

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        max.setText("");
    }//GEN-LAST:event_maxMouseClicked

    private void maxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxKeyTyped
        validations.validateNumber(max, evt);
    }//GEN-LAST:event_maxKeyTyped

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        desc.setText("");
    }//GEN-LAST:event_descMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateFertilizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateFertilizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateFertilizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateFertilizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateFertilizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox comboSensorType;
    private javax.swing.JTextArea crops;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField max;
    private javax.swing.JTextField min;
    private javax.swing.JTextField qty;
    // End of variables declaration//GEN-END:variables
}
